In [4]:
import pandas as pd

import numpy as np

In [30]:
#csv schematics

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df.shape

(2810, 24)

In [7]:
#exonerations by race

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

race = df.loc[:,"Race"]

race_value = race.value_counts()

black_total = (1397 / 2804) * 100

white_total = (1009 / 2804) * 100

hispanic_total = (334 / 2804) * 100

native_total = (19 / 2804) * 100

#5 was removed from total individuals because of unknown race and there are 2809 total individuals because 2810 rows including header

print(race_value)

print(black_total)

print(white_total)

print(hispanic_total)

print(native_total)

black_proportion = 475,900 / 1,439,808 

#black proportion is 33%

white_proportion = (436,500 / 1,439,808) 

#white proportion is 30%

hispanic_proportion = (336,500 / 1,439,808) 

#hispanic proportion is 23%

native_proportion = (22,744 / 1,439,808)

#native proportion is 1.5%

Black              1397
White              1009
Hispanic            334
Asian                29
Native American      19
Other                17
Don't Know            5
Name: Race, dtype: int64
49.82168330955778
35.984308131241086
11.911554921540656
0.6776034236804565

In [18]:
#exoneration rate by crime

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

crime = df.loc[:, "Worst Crime Display"]

crime_table = crime.value_counts()

murder_rate = (1079/2809) * 100

drug_rate = (390/2809) * 100

rape_rate = (343/2809) * 100

child_rate = (294/2809) * 100

robbery_rate = (139/2809) * 100

assault_rate = (105/2809) * 100

theft_rate = (20/2809) * 100

traffic_rate = (7/2809) * 100

forgery_rate = (4/2809) * 100

false_report_rate = (1/2809) * 100

print(crime_table)

print(murder_rate)

print(drug_rate)

print(rape_rate)

print(child_rate)

print(robbery_rate)

print(assault_rate)

print(theft_rate)

print(traffic_rate)

print(forgery_rate)

print(false_report_rate)

Murder                           1079
Drug Possession or Sale           390
Sexual Assault                    343
Child Sex Abuse                   294
Robbery                           139
Assault                           105
Attempted Murder                   67
Manslaughter                       53
Weapon Possession or Sale          53
Fraud                              45
Sex Offender Registration          32
Arson                              23
Theft                              20
Burglary/Unlawful Entry            20
Kidnapping                         16
Other Nonviolent Felony            16
Child Abuse                        11
Other Violent Felony               11
Accessory to Murder                 9
Other Nonviolent Misdemeanor        8
Tax Evasion/Fraud                   7
Traffic Offense                     7
Attempt, Violent                    6
Threats                             6
Bribery                             6
Perjury                             5
Supporting Terrorism                4
Immigration                         4
Forgery                             4
Destruction of Property             3
Solicitation                        3
Possession of Stolen Property       3
Other Violent Misdemeanor           3
Conspiracy                          2
Official Misconduct                 2
Menacing                            2
Stalking                            2
Failure to Pay Child Support        2
Obstruction of Justice              1
Military Justice Offense            1
Filing a False Report               1
Harassment                          1
Dependent Adult Abuse               1
Name: Worst Crime Display, dtype: int64
38.412246351014595
13.883944464222143
12.210751156995373
10.466358134567463
4.948380206479174
3.7379850480598074
0.711997152011392
0.2491990032039872
0.1423994304022784
0.0355998576005696

In [4]:
#total DNA exonerations

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

dna = df["DNA"]

dna_only = dna.dropna()

dna_value = dna_only.value_counts()

dna_rate = ((dna_value) / 2809) * 100

print(dna_rate)

DNA    19.188323
ï¿½       0.035600
Name: DNA, dtype: float64

In [55]:
#murder and false evidence

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('WorstCrimeDisplay == "Murder" and FalseEvidence == "Yes"')

print(df1)

            Last Name First Name   Age      Race   Sex                 State  \
13              Adams    Kenneth  21.0     Black  Male              Illinois
24    Aguirre-Jarquin   Clemente  24.0  Hispanic  Male               Florida
48         Allen, Jr.     George  25.0     Black  Male              Missouri
53             Alonzo    Quintin  21.0  Hispanic  Male                 Texas
66               Amor    William  39.0     White  Male              Illinois
...               ...        ...   ...       ...   ...                   ...
2755     Winfrey, Sr.    Richard  49.0     White  Male                 Texas
2763             Witt    Drayton  18.0     White  Male               Arizona
2785           Wright  Cleveland  20.0     Black  Male  District of Columbia
2794         Yarbough    Anthony  18.0     Black  Male              New York
2799       Young, Jr.        Dan  30.0     Black  Male              Illinois

           County                Tags WorstCrimeDisplay  \
13           Cook      CDC;#H;#IO;#JI            Murder
24       Seminole               H;#IO            Murder
48           Cole               H;#IO            Murder
53         Dallas              CIU;#H            Murder
66         DuPage        A;#H;#IO;#NC            Murder
...           ...                 ...               ...
2755  San Jacinto               H;#JI            Murder
2763     Maricopa  CV;#H;#NC;#SBS;#IO            Murder
2785          NaN               H;#IO            Murder
2794        Kings     CDC;#CIU;#CV;#H            Murder
2799         Cook           A;#CDC;#H            Murder

                           List Add'l Crimes Recode  ...    *   FC  MWID  \
13                                 Rape;#Kidnapping  ...  NaN  NaN  MWID
24                          Burglary/Unlawful Entry  ...  NaN  NaN   NaN
48    Rape;#Sexual Assault;#Burglary/Unlawful Entry  ...    *   FC   NaN
53                                          Assault  ...  NaN  NaN  MWID
66                                            Arson  ...  NaN   FC   NaN
...                                             ...  ...  ...  ...   ...
2755                                            NaN  ...  NaN  NaN   NaN
2763                                            NaN  ...  NaN  NaN   NaN
2785  Sexual Assault;#Assault;#Other Violent Felony  ...    *  NaN   NaN
2794                                            NaN  ...  NaN   FC   NaN
2799              Sexual Assault;#Arson;#Kidnapping  ...    *   FC   NaN

     FalseEvidence  P/FA   OM  ILD Posting Date  \
13             Yes  P/FA   OM  NaN      8/29/11
24             Yes  P/FA  NaN  ILD     11/11/18
48             Yes  P/FA   OM  NaN      1/18/13
53             Yes  P/FA   OM  ILD     11/11/19
66             Yes   NaN  NaN  NaN      2/23/18
...            ...   ...  ...  ...          ...
2755           Yes  P/FA  NaN  NaN      8/29/11
2763           Yes   NaN  NaN  NaN      11/1/12
2785           Yes  P/FA   OM  NaN       2/3/14
2794           Yes  P/FA   OM  ILD      2/11/14
2799           Yes  P/FA   OM  NaN      8/29/11

                             OM Tags Date of Crime Year
13            PR;#OF;#WH;#NW;#KP;#WT              1,978
24                               NaN              2,004
48           OF;#FA;#WH;#NW;#INT;#PJ              1,982
53    PR;#OF;#WH;#NW;#KP;#WT;#PJ;#PL              2,001
66                               NaN              1,995
...                              ...                ...
2755                             NaN              2,004
2763                             NaN              2,000
2785                  FA;#WH;#NW;#PJ              1,978
2794         OF;#WH;#NW;#WT;#INT;#PJ              1,992
2799             OF;#WH;#NW;#WT;#INT              1,990

[275 rows x 24 columns]

In [5]:
#total false evidence 

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

FE = df["FalseEvidence"]

FE_only = FE.dropna()

total = FE_only.value_counts()

print(total)

percent = (681/2809) * 100

print(percent)

Yes    681
Name: FalseEvidence, dtype: int64
24.243503025987895

In [20]:
#drug crimes and false evidence

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('WorstCrimeDisplay == "Drug Possession or Sale" and FalseEvidence == "Yes"')

print(df1)

percent = 133/681 * 100

print(percent)

       Last Name First Name   Age      Race     Sex   State      County  \
12         Adams     Johnny  52.0     Black    Male   Texas      Harris
28     Albritton        Amy  43.0     White  Female   Texas      Harris
33       Alegria      Megan  20.0     White  Female   Texas      Harris
67         Amory       Earl  38.0     Black    Male   Texas      Harris
105          Ash     Steven  54.0     White    Male  Oregon  MultnYesah
...          ...        ...   ...       ...     ...     ...         ...
2691     Wilkins      Geary  40.0     Black    Male   Texas      Harris
2696    Williams     Arthur  34.0     Black    Male   Texas      Harris
2788      Wright     Summer  20.0     Black  Female   Texas      Harris
2793  Yac-Garcia       Jose  27.0  Hispanic    Male   Texas      Harris
2804     Zarzoza   Jonathan  18.0     White    Male   Texas      Harris

                  Tags        WorstCrimeDisplay List Add'l Crimes Recode  ...  \
12          CIU;#NC;#P  Drug Possession or Sale                      NaN  ...
28       CIU;#F;#NC;#P  Drug Possession or Sale                      NaN  ...
33       CIU;#F;#NC;#P  Drug Possession or Sale                      NaN  ...
67          CIU;#NC;#P  Drug Possession or Sale                      NaN  ...
105         CIU;#NC;#P  Drug Possession or Sale                      NaN  ...
...                ...                      ...                      ...  ...
2691             NC;#P  Drug Possession or Sale                      NaN  ...
2696        CIU;#NC;#P  Drug Possession or Sale                      NaN  ...
2788  CIU;#F;#M;#NC;#P  Drug Possession or Sale                      NaN  ...
2793        CIU;#NC;#P  Drug Possession or Sale                      NaN  ...
2804             NC;#P  Drug Possession or Sale                      NaN  ...

        *   FC  MWID FalseEvidence Perjury OfficialMisconduct  ILD  \
12    NaN  NaN   NaN           Yes     NaN                NaN  NaN
28    NaN  NaN   NaN           Yes     NaN                NaN  NaN
33    NaN  NaN   NaN           Yes     NaN                NaN  NaN
67    NaN  NaN   NaN           Yes     NaN                NaN  NaN
105   NaN  NaN   NaN           Yes     NaN                NaN  NaN
...   ...  ...   ...           ...     ...                ...  ...
2691  NaN  NaN   NaN           Yes     NaN                NaN  NaN
2696  NaN  NaN   NaN           Yes     NaN                NaN  NaN
2788  NaN  NaN   NaN           Yes     NaN                NaN  NaN
2793  NaN  NaN   NaN           Yes     NaN                NaN  NaN
2804  NaN  NaN   NaN           Yes     NaN                NaN  NaN

     Posting Date Yes Tags Date of Crime Year
12        3/18/16      NaN              2,008
28        7/22/16      NaN              2,010
33        4/30/20      NaN              2,011
67       12/22/16      NaN              2,009
105       12/9/16      NaN              2,012
...           ...      ...                ...
2691      5/28/14      NaN              2,013
2696      11/5/16      NaN              2,005
2788      11/2/15      NaN              2,013
2793      11/3/15      NaN              2,015
2804      6/16/20      NaN              2,013

[133 rows x 24 columns]
19.530102790014684

In [22]:
#sexual assault and false evidence

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('WorstCrimeDisplay == "Sexual Assault" and FalseEvidence == "Yes"')

print(df1)

percent = 111/681 * 100

print(percent)

        Last Name    First Name   Age      Race   Sex          State  \
1           Abdal  Warith Habib  43.0     Black  Male       New York
34      Alejandro       Gilbert  35.0  Hispanic  Male          Texas
38      Alexander       Richard  29.0     Black  Male        Indiana
107        Atkins        Herman  19.0     Black  Male     California
162     Barnhouse       William  35.0     White  Male        Indiana
...           ...           ...   ...       ...   ...            ...
2734       Willis          John  42.0     Black  Male       Illinois
2761         Wise         Korey  16.0     Black  Male       New York
2768      Woodall          Glen  28.0     White  Male  West Virginia
2786  Wright, Jr.        Harold  32.0     Black  Male     Washington
2790        Wyatt   Rickey Dale  25.0     Black  Male          Texas

          County     Tags WorstCrimeDisplay  \
1           Erie       IO    Sexual Assault
34        Uvalde      NaN    Sexual Assault
38    St. Joseph      NaN    Sexual Assault
107    Riverside       IO    Sexual Assault
162     Delaware       IO    Sexual Assault
...          ...      ...               ...
2734        Cook      NaN    Sexual Assault
2761    New York  CDC;#IO    Sexual Assault
2768      Cabell      NaN    Sexual Assault
2786      Pierce       NC    Sexual Assault
2790      Dallas  CIU;#IO    Sexual Assault

                               List Add'l Crimes Recode  ...    *   FC  MWID  \
1                                               Robbery  ...  NaN  NaN  MWID
34                                                  NaN  ...  NaN  NaN  MWID
38    Robbery;#Other Violent Felony;#Burglary/Unlawf...  ...  NaN  NaN  MWID
107                                                 NaN  ...  NaN  NaN  MWID
162                                                 NaN  ...  NaN  NaN  MWID
...                                                 ...  ...  ...  ...   ...
2734                                            Robbery  ...  NaN  NaN  MWID
2761                      Assault;#Other Violent Felony  ...  NaN   FC   NaN
2768                                Robbery;#Kidnapping  ...  NaN  NaN  MWID
2786                                                NaN  ...  NaN  NaN   NaN
2790                      Assault;#Other Violent Felony  ...  NaN  NaN  MWID

     FalseEvidence Perjury OfficialMisconduct  ILD Posting Date  \
1              Yes     NaN                Yes  NaN      8/29/11
34             Yes     Yes                Yes  NaN      8/29/11
38             Yes     NaN                NaN  NaN      8/29/11
107            Yes     NaN                NaN  NaN      8/29/11
162            Yes     NaN                NaN  NaN      5/14/17
...            ...     ...                ...  ...          ...
2734           Yes     Yes                Yes  NaN      8/29/11
2761           Yes     Yes                Yes  NaN      8/29/11
2768           Yes     Yes                Yes  NaN      8/29/11
2786           Yes     Yes                Yes  NaN      9/27/13
2790           Yes     Yes                Yes  ILD      8/30/12

                    Yes Tags Date of Crime Year
1             OF;#WH;#NW;#WT              1,982
34    OF;#FA;#WH;#NW;#WT;#PJ              1,990
38                       NaN              1,996
107                      NaN              1,986
162                      NaN              1,992
...                      ...                ...
2734      PR;#FA;#WH;#NW;#PJ              1,990
2761         OF;#WH;#NW;#INT              1,989
2768      PR;#FA;#WH;#NW;#PJ              1,987
2786          PR;#WH;#NW;#PL              2,004
2790  PR;#OF;#WH;#NW;#WT;#PJ              1,980

[111 rows x 24 columns]
16.299559471365637

In [24]:
#child abuse and false evidence

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('WorstCrimeDisplay == "Child Sex Abuse" and FalseEvidence == "Yes"')

print(df1)

percent = 75/681 * 100

print(percent)

     Last Name First Name   Age   Race     Sex          State          County  \
125   Baba-Ali      Amine  31.0  Other    Male       New York          Queens
132       Bain   Fredrick  29.0  White    Male         Oregon         Malheur
133       Bain      James  19.0  Black    Male        Florida            Polk
146    Ballard    Frances  54.0  White  Female      Tennessee          Shelby
155      Baran    Bernard  18.0  White    Male  Massachusetts       Berkshire
...        ...        ...   ...    ...     ...            ...             ...
2611  Washburn    Michael  20.0  White    Male  Massachusetts         Bristol
2713  Williams      Jimmy  20.0  Black    Male           Ohio          Summit
2771     Woods    Anthony  20.0  Black    Male       Missouri  St. Louis City
2776   Woolson     Skippy  34.0  White    Male       New York          Oswego
2780      Wosu        Joy  33.0  Black  Female       New York            Erie

                Tags WorstCrimeDisplay             List Add'l Crimes Recode  \
125           CV;#NC   Child Sex Abuse                                  NaN
132       CV;#IO;#NC   Child Sex Abuse                                  NaN
133           CV;#IO   Child Sex Abuse  Kidnapping;#Burglary/Unlawful Entry
146   CSH;#CV;#F;#NC   Child Sex Abuse                                  NaN
155      CSH;#CV;#NC   Child Sex Abuse                              Assault
...              ...               ...                                  ...
2611          CV;#NC   Child Sex Abuse                                  NaN
2713              CV   Child Sex Abuse                                  NaN
2771              CV   Child Sex Abuse                 Other Violent Felony
2776          CV;#NC   Child Sex Abuse                          Child Abuse
2780       CV;#F;#NC   Child Sex Abuse                                  NaN

      ...    *   FC  MWID FalseEvidence Perjury OfficialMisconduct  ILD  \
125   ...  NaN  NaN   NaN           Yes     Yes                NaN  ILD
132   ...  NaN  NaN   NaN           Yes     Yes                NaN  ILD
133   ...  NaN  NaN  MWID           Yes     NaN                NaN  NaN
146   ...  NaN  NaN   NaN           Yes     Yes                Yes  NaN
155   ...  NaN  NaN   NaN           Yes     Yes                Yes  ILD
...   ...  ...  ...   ...           ...     ...                ...  ...
2611  ...  NaN  NaN   NaN           Yes     Yes                Yes  ILD
2713  ...  NaN  NaN  MWID           Yes     NaN                Yes  NaN
2771  ...  NaN  NaN  MWID           Yes     NaN                NaN  NaN
2776  ...  NaN  NaN   NaN           Yes     Yes                NaN  ILD
2780  ...  NaN  NaN   NaN           Yes     Yes                NaN  ILD

     Posting Date                    Yes Tags Date of Crime Year
125       8/31/11                         NaN              1,988
132       8/28/20                         NaN              2,007
133       8/29/11                         NaN              1,974
146       3/21/13  PR;#OF;#CW;#WH;#NW;#KP;#WT              1,984
155       8/29/11              PR;#WH;#NW;#WT              1,984
...           ...                         ...                ...
2611     11/17/17                  OF;#NW;#WT              1,994
2713      8/29/11                  OF;#NW;#WT              1,990
2771      8/29/11                         NaN              1,983
2776      3/18/17                         NaN              2,011
2780     12/18/13                         NaN              1,991

[75 rows x 24 columns]
11.013215859030836

In [26]:
#robbery and false evidence

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('WorstCrimeDisplay == "Robbery" and FalseEvidence == "Yes"')

print(df1)

percent = 13/681 * 100

print(percent)

       Last Name       First Name   Age      Race   Sex       State  \
137        Baker         Dontrell  18.0     Black  Male     Florida
311       Bryant            Andre  20.0     Black  Male     Florida
474   Clark, Jr.            Royal  24.0     Black  Male   Louisiana
518       Cooper            Keith  29.0     Black  Male     Indiana
536     Courtney          Sedrick  23.0     Black  Male   OklahYesa
859        Gandy           Robert  24.0     Black  Male       Texas
1055      Harris          Derrick  21.0     Black  Male  California
1209     Jackson           Dwayne  18.0     Black  Male      Nevada
1673    Mervilus         Emmanuel  22.0     Black  Male  New Jersey
1827       Ochoa            James  19.0  Hispanic  Male  California
2004    Prentice             Mark  27.0     White  Male    New York
2121   Rodriguez          Jeffrey  24.0  Hispanic  Male  California
2264     Showers  Kurtis DeAngelo  28.0     Black  Male    Michigan

           County        Tags WorstCrimeDisplay  \
137      Pinellas         NaN           Robbery
311       Manatee      CV;#IO           Robbery
474     Jefferson      CV;#IO           Robbery
518       Elkhart  CV;#IO;#JI           Robbery
536         Tulsa          IO           Robbery
859        Harris         CDC           Robbery
1055  Los Angeles     CIU;#IO           Robbery
1209        Clark           P           Robbery
1673        Union         NaN           Robbery
1827       Orange           P           Robbery
2004    TYespkins           P           Robbery
2121  Santa Clara         NaN           Robbery
2264        Wayne         NaN           Robbery

                             List Add'l Crimes Recode  ...    *   FC  MWID  \
137                                               NaN  ...    *  NaN  MWID
311                                               NaN  ...  NaN  NaN  MWID
474                                               NaN  ...  NaN  NaN  MWID
518                                               NaN  ...    *  NaN  MWID
536                           Burglary/Unlawful Entry  ...  NaN  NaN  MWID
859                                               NaN  ...  NaN  NaN   NaN
1055  Gun Possession or Sale;#Other Nonviolent Felony  ...  NaN  NaN  MWID
1209                                              NaN  ...  NaN  NaN   NaN
1673                                          Assault  ...  NaN  NaN  MWID
1827                                              NaN  ...  NaN  NaN  MWID
2004                 Assault;#Burglary/Unlawful Entry  ...  NaN  NaN  MWID
2121                                              NaN  ...  NaN  NaN  MWID
2264                           Gun Possession or Sale  ...  NaN  NaN  MWID

     FalseEvidence Perjury OfficialMisconduct  ILD Posting Date  \
137            Yes     NaN                NaN  NaN      9/14/15
311            Yes     NaN                Yes  NaN      10/6/15
474            Yes     NaN                NaN  NaN      6/28/19
518            Yes     Yes                Yes  ILD      2/18/17
536            Yes     NaN                NaN  NaN      8/30/12
859            Yes     Yes                NaN  NaN      6/26/20
1055           Yes     NaN                Yes  NaN     10/26/20
1209           Yes     NaN                NaN  NaN      3/30/12
1673           Yes     NaN                Yes  ILD       5/3/18
1827           Yes     NaN                Yes  NaN      8/29/11
2004           Yes     Yes                Yes  NaN     10/31/14
2121           Yes     NaN                NaN  ILD      8/29/11
2264           Yes     NaN                NaN  NaN      8/29/11

                Yes Tags Date of Crime Year
137                  NaN              1,996
311               OF;#WH              2,006
474                  NaN              2,001
518   OF;#WH;#NW;#WT;#PJ              1,996
536                  NaN              1,995
859                  NaN              1,989
1055          OF;#NW;#WT              2,013
1209                 NaN              2,001
1673      PR;#OF;#NW;#WT              2,006
1827          OF;#NW;#WT              2,005
2004  OF;#WH;#NW;#WT;#PJ              1,988
2121                 NaN              2,001
2264                 NaN              1,993

[13 rows x 24 columns]
1.908957415565345

In [31]:
#false evidence in top crimes

total_percent_false_ev = 40.4 + 19.5 + 16.3 + 11 + 1.0 + 1.9

print(total_percent_false_ev)

90.10000000000001

In [28]:
#assault and false evidence

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('WorstCrimeDisplay == "Assault" and FalseEvidence == "Yes"')

print(df1)

percent = 7/681 * 100

print(percent)

      Last Name First Name   Age   Race     Sex        State       County  \
1045     Harper      James  45.0  White    Male    Tennessee         Knox
1111  Herskovic      Mayer  20.0  White    Male     New York        Kings
1192  Hutchison    Leonard  39.0  White    Male    Tennessee         Knox
1199      Irons   Jonathan  16.0  Black    Male     Missouri  St. Charles
2267      Shved       Olga  23.0  White  Female   Washington     Franklin
2385     Stubbs      Leigh  20.0  White  Female  Mississippi      Lincoln
2536      Vance      Tammy  31.0  White  Female  Mississippi      Lincoln

           Tags WorstCrimeDisplay  \
1045         PH           Assault
1111        NaN           Assault
1192        NaN           Assault
1199        NaN           Assault
2267  CV;#F;#NC           Assault
2385  F;#IO;#NC           Assault
2536  F;#IO;#NC           Assault

                              List Add'l Crimes Recode  ...    *   FC  MWID  \
1045                           Burglary/Unlawful Entry  ...  NaN  NaN  MWID
1111                  Kidnapping;#Other Violent Felony  ...  NaN  NaN   NaN
1192  Burglary/Unlawful Entry;#Other Nonviolent Felony  ...  NaN  NaN  MWID
1199  Burglary/Unlawful Entry;#Illegal Use of a Weapon  ...  NaN   FC  MWID
2267                                               NaN  ...  NaN  NaN   NaN
2385                    Theft;#Drug Possession or Sale  ...  NaN  NaN   NaN
2536                    Theft;#Drug Possession or Sale  ...  NaN  NaN   NaN

     FalseEvidence Perjury OfficialMisconduct  ILD Posting Date  \
1045           Yes     Yes                Yes  NaN     11/14/17
1111           Yes     Yes                NaN  ILD     11/26/18
1192           Yes     Yes                Yes  NaN     11/14/17
1199           Yes     Yes                Yes  ILD      7/20/20
2267           Yes     NaN                NaN  NaN      7/31/14
2385           Yes     NaN                Yes  NaN     10/25/18
2536           Yes     NaN                Yes  NaN     10/25/18

                            Yes Tags Date of Crime Year
1045          PR;#OF;#FA;#WH;#NW;#PJ              1,982
1111                             NaN              2,013
1192      PR;#OF;#FA;#WH;#NW;#WT;#PJ              1,982
1199  PR;#OF;#WH;#NW;#KP;#WT;#PJ;#PL              1,997
2267                             NaN              2,006
2385                          PR;#WH              2,000
2536                          PR;#WH              2,000

[7 rows x 24 columns]
1.0279001468428781

In [8]:
#perjury and false evidence

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('FalseEvidence == "Yes" and Perjury == "Yes"')

print(df1)

ev_experts = (321/681) * 100

print(ev_experts)

#structural problem with forensics experts and testimony contributing to serious wrongful convictions caused by ev

            Last Name   First Name   Age      Race   Sex       State  \
13              Adams      Kenneth  21.0     Black  Male    Illinois
24    Aguirre-Jarquin     Clemente  24.0  Hispanic  Male     Florida
34          Alejandro      Gilbert  35.0  Hispanic  Male       Texas
48         Allen, Jr.       George  25.0     Black  Male    Missouri
53             Alonzo      Quintin  21.0  Hispanic  Male       Texas
...               ...          ...   ...       ...   ...         ...
2786      Wright, Jr.       Harold  32.0     Black  Male  Washington
2790            Wyatt  Rickey Dale  25.0     Black  Male       Texas
2794         Yarbough      Anthony  18.0     Black  Male    New York
2799       Young, Jr.          Dan  30.0     Black  Male    Illinois
2806           Zimmer       Walter  40.0     White  Male        Ohio

        County             Tags WorstCrimeDisplay  \
13        Cook   CDC;#H;#IO;#JI            Murder
24    Seminole            H;#IO            Murder
34      Uvalde              NaN    Sexual Assault
48        Cole            H;#IO            Murder
53      Dallas           CIU;#H            Murder
...        ...              ...               ...
2786    Pierce               NC    Sexual Assault
2790    Dallas          CIU;#IO    Sexual Assault
2794     Kings  CDC;#CIU;#CV;#H            Murder
2799      Cook        A;#CDC;#H            Murder
2806  Cuyahoga       CDC;#H;#IO      Manslaughter

                               List Add'l Crimes Recode  ...    *   FC  MWID  \
13                                     Rape;#Kidnapping  ...  NaN  NaN  MWID
24                              Burglary/Unlawful Entry  ...  NaN  NaN   NaN
34                                                  NaN  ...  NaN  NaN  MWID
48        Rape;#Sexual Assault;#Burglary/Unlawful Entry  ...    *   FC   NaN
53                                              Assault  ...  NaN  NaN  MWID
...                                                 ...  ...  ...  ...   ...
2786                                                NaN  ...  NaN  NaN   NaN
2790                      Assault;#Other Violent Felony  ...  NaN  NaN  MWID
2794                                                NaN  ...  NaN   FC   NaN
2799                  Sexual Assault;#Arson;#Kidnapping  ...    *   FC   NaN
2806  Attempted Murder;#Robbery;#Assault;#Kidnapping...  ...    *  NaN   NaN

     FalseEvidence Perjury   OM  ILD Posting Date  \
13             Yes     Yes   OM  NaN      8/29/11
24             Yes     Yes  NaN  ILD     11/11/18
34             Yes     Yes   OM  NaN      8/29/11
48             Yes     Yes   OM  NaN      1/18/13
53             Yes     Yes   OM  ILD     11/11/19
...            ...     ...  ...  ...          ...
2786           Yes     Yes   OM  NaN      9/27/13
2790           Yes     Yes   OM  ILD      8/30/12
2794           Yes     Yes   OM  ILD      2/11/14
2799           Yes     Yes   OM  NaN      8/29/11
2806           Yes     Yes   OM  NaN      10/4/13

                             OM Tags Date of Crime Year
13            PR;#OF;#WH;#NW;#KP;#WT              1,978
24                               NaN              2,004
34            OF;#FA;#WH;#NW;#WT;#PJ              1,990
48           OF;#FA;#WH;#NW;#INT;#PJ              1,982
53    PR;#OF;#WH;#NW;#KP;#WT;#PJ;#PL              2,001
...                              ...                ...
2786                  PR;#WH;#NW;#PL              2,004
2790          PR;#OF;#WH;#NW;#WT;#PJ              1,980
2794         OF;#WH;#NW;#WT;#INT;#PJ              1,992
2799             OF;#WH;#NW;#WT;#INT              1,990
2806                  FA;#WH;#NW;#PJ              1,997

[321 rows x 24 columns]
47.136563876651984

In [13]:
#perjury and false evidence and official misconduct

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('FalseEvidence == "Yes" and Perjury == "Yes" and OfficialMisconduct == "Yes"')

print(df1)

ev_experts = (239/681) * 100

print(ev_experts)

        Last Name   First Name   Age      Race   Sex           State  \
13          Adams      Kenneth  21.0     Black  Male        Illinois
34      Alejandro      Gilbert  35.0  Hispanic  Male           Texas
48     Allen, Jr.       George  25.0     Black  Male        Missouri
53         Alonzo      Quintin  21.0  Hispanic  Male           Texas
96      Armstrong      LaMonte  38.0     Black  Male  North Carolina
...           ...          ...   ...       ...   ...             ...
2786  Wright, Jr.       Harold  32.0     Black  Male      Washington
2790        Wyatt  Rickey Dale  25.0     Black  Male           Texas
2794     Yarbough      Anthony  18.0     Black  Male        New York
2799   Young, Jr.          Dan  30.0     Black  Male        Illinois
2806       Zimmer       Walter  40.0     White  Male            Ohio

        County             Tags WorstCrimeDisplay  \
13        Cook   CDC;#H;#IO;#JI            Murder
34      Uvalde              NaN    Sexual Assault
48        Cole            H;#IO            Murder
53      Dallas           CIU;#H            Murder
96    Guilford   CDC;#H;#IO;#JI            Murder
...        ...              ...               ...
2786    Pierce               NC    Sexual Assault
2790    Dallas          CIU;#IO    Sexual Assault
2794     Kings  CDC;#CIU;#CV;#H            Murder
2799      Cook        A;#CDC;#H            Murder
2806  Cuyahoga       CDC;#H;#IO      Manslaughter

                               List Add'l Crimes Recode  ...    *   FC  MWID  \
13                                     Rape;#Kidnapping  ...  NaN  NaN  MWID
34                                                  NaN  ...  NaN  NaN  MWID
48        Rape;#Sexual Assault;#Burglary/Unlawful Entry  ...    *   FC   NaN
53                                              Assault  ...  NaN  NaN  MWID
96                                                  NaN  ...    *  NaN   NaN
...                                                 ...  ...  ...  ...   ...
2786                                                NaN  ...  NaN  NaN   NaN
2790                      Assault;#Other Violent Felony  ...  NaN  NaN  MWID
2794                                                NaN  ...  NaN   FC   NaN
2799                  Sexual Assault;#Arson;#Kidnapping  ...    *   FC   NaN
2806  Attempted Murder;#Robbery;#Assault;#Kidnapping...  ...    *  NaN   NaN

     FalseEvidence Perjury OfficialMisconduct  ILD Posting Date  \
13             Yes     Yes                Yes  NaN      8/29/11
34             Yes     Yes                Yes  NaN      8/29/11
48             Yes     Yes                Yes  NaN      1/18/13
53             Yes     Yes                Yes  ILD     11/11/19
96             Yes     Yes                Yes  NaN      3/19/13
...            ...     ...                ...  ...          ...
2786           Yes     Yes                Yes  NaN      9/27/13
2790           Yes     Yes                Yes  ILD      8/30/12
2794           Yes     Yes                Yes  ILD      2/11/14
2799           Yes     Yes                Yes  NaN      8/29/11
2806           Yes     Yes                Yes  NaN      10/4/13

                            Yes Tags Date of Crime Year
13            PR;#OF;#WH;#NW;#KP;#WT              1,978
34            OF;#FA;#WH;#NW;#WT;#PJ              1,990
48           OF;#FA;#WH;#NW;#INT;#PJ              1,982
53    PR;#OF;#WH;#NW;#KP;#WT;#PJ;#PL              2,001
96                            OF;#WH              1,988
...                              ...                ...
2786                  PR;#WH;#NW;#PL              2,004
2790          PR;#OF;#WH;#NW;#WT;#PJ              1,980
2794         OF;#WH;#NW;#WT;#INT;#PJ              1,992
2799             OF;#WH;#NW;#WT;#INT              1,990
2806                  FA;#WH;#NW;#PJ              1,997

[239 rows x 24 columns]
35.095447870778266

In [15]:
#perjury and official misconduct

df2 = df.query('Perjury == "Yes" and OfficialMisconduct == "Yes"')

print(df2)

PE_only = df2.dropna()

total = PE_only.value_counts()

percent = (1247/1695) * 100

print(percent)

       Last Name   First Name   Age      Race   Sex         State  \
2      Abernathy  Christopher  17.0     White  Male      Illinois
5          Adams      Anthony  26.0  Hispanic  Male    California
8          Adams     Demetris  22.0     Black  Male      Illinois
9          Adams      Don Ray  32.0     Black  Male  Pennsylvania
13         Adams      Kenneth  21.0     Black  Male      Illinois
...          ...          ...   ...       ...   ...           ...
2799  Young, Jr.          Dan  30.0     Black  Male      Illinois
2801     Yurtman        Ersan  18.0  Hispanic  Male         Texas
2802       Yusuf       Yassin  19.0     Black  Male        Fed-TN
2806      Zimmer       Walter  40.0     White  Male          Ohio
2808  Zinkiewicz       Tyrone  38.0     White  Male          Ohio

            County              Tags        WorstCrimeDisplay  \
2             Cook    CIU;#CV;#H;#IO                   Murder
5      Los Angeles              H;#P             Manslaughter
8             Cook    CIU;#IO;#NC;#P  Drug Possession or Sale
9     Philadelphia                 H                   Murder
13            Cook    CDC;#H;#IO;#JI                   Murder
...            ...               ...                      ...
2799          Cook         A;#CDC;#H                   Murder
2801         Bexar  CDC;#CIU;#CV;#IO          Child Sex Abuse
2802      (Middle)           FED;#NC     Other Violent Felony
2806      Cuyahoga        CDC;#H;#IO             Manslaughter
2808   MontgYesery            CV;#NC  Other Nonviolent Felony

                               List Add'l Crimes Recode  ... MistakenWitness  \
2                                         Rape;#Robbery  ...             NaN
5                                                   NaN  ...             NaN
8                                                   NaN  ...             NaN
9                                                   NaN  ...             NaN
13                                     Rape;#Kidnapping  ...             Yes
...                                                 ...  ...             ...
2799                  Sexual Assault;#Arson;#Kidnapping  ...             NaN
2801                                                NaN  ...             NaN
2802                                         Conspiracy  ...             NaN
2806  Attempted Murder;#Robbery;#Assault;#Kidnapping...  ...             NaN
2808                                                NaN  ...             NaN

      FalseEvidence  Perjury OfficialMisconduct  ILD Posting Date  \
2               NaN      Yes                Yes  NaN      2/13/15
5               NaN      Yes                Yes  NaN      5/18/12
8               NaN      Yes                Yes  NaN      4/13/20
9               NaN      Yes                Yes  NaN      3/13/12
13              Yes      Yes                Yes  NaN      8/29/11
...             ...      ...                ...  ...          ...
2799            Yes      Yes                Yes  NaN      8/29/11
2801            NaN      Yes                Yes  NaN      8/10/20
2802            NaN      Yes                Yes  NaN      3/18/16
2806            Yes      Yes                Yes  NaN      10/4/13
2808            NaN      Yes                Yes  NaN     10/25/14

                        Yes Tags Date of Crime Year Unnamed: 24  CIU
2                OF;#WH;#NW;#INT              1,984         NaN  Yes
5                 OF;#WH;#NW;#WT              1,996         NaN  NaN
8                     OF;#WH;#NW              2,004         NaN  Yes
9                 OF;#WH;#NW;#WT              1,990         NaN  NaN
13        PR;#OF;#WH;#NW;#KP;#WT              1,978         NaN  NaN
...                          ...                ...         ...  ...
2799         OF;#WH;#NW;#WT;#INT              1,990         NaN  NaN
2801          PR;#OF;#WH;#NW;#WT              1,992         NaN  NaN
2802  PR;#OF;#WH;#NW;#KP;#WT;#PJ              2,009         NaN  NaN
2806              FA;#WH;#NW;#PJ              1,997         NaN  NaN
2808                      PR;#WH              1,988         NaN  NaN

[1247 rows x 26 columns]
73.5693215339233

In [16]:
#total perjury

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

PE = df["Perjury"]

PE_only = PE.dropna()

total = PE_only.value_counts()

print(total)

percent = (1247/1695) * 100

print(percent)

Yes    1695
Name: Perjury, dtype: int64
73.5693215339233

In [33]:
#percent total perjury

perjury_total = 1695 / 2809 * 100

print (perjury_total)

60.34175863296547

In [45]:
#total mistaken witness


df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

MW = df["MistakenWitness"]

MW_only = MW.dropna()

total = MW_only.value_counts()

print(total)

Yes    792
Name: MistakenWitness, dtype: int64

In [46]:
#mistaken witness and perjury

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')
df1 = df.query('MistakenWitness == "Yes" and Perjury == "Yes"')

print(df1)

percent = (267/792) * 100

print(percent)

      Last Name    First Name   Age             Race   Sex          State  \
13        Adams       Kenneth  21.0            Black  Male       Illinois
15        Adams  Randall Dale  28.0            White  Male          Texas
34    Alejandro       Gilbert  35.0         Hispanic  Male          Texas
37    Alexander       Malcolm  19.0            Black  Male      Louisiana
39       Alford       Herbert  38.0            Black  Male       Michigan
...         ...           ...   ...              ...   ...            ...
2768    Woodall          Glen  28.0            White  Male  West Virginia
2789  Wurdemann          John  29.0  Native American  Male          Idaho
2790      Wyatt   Rickey Dale  25.0            Black  Male          Texas
2791   Wyniemko       Kenneth  42.0            White  Male       Michigan
2795     Yarris      Nicholas  20.0            White  Male   Pennsylvania

         County            Tags WorstCrimeDisplay  \
13         Cook  CDC;#H;#IO;#JI            Murder
15       Dallas          CDC;#H            Murder
34       Uvalde             NaN    Sexual Assault
37    Jefferson              IO    Sexual Assault
39       Ingham               H            Murder
...         ...             ...               ...
2768     Cabell             NaN    Sexual Assault
2789     Canyon          A;#CDC  Attempted Murder
2790     Dallas         CIU;#IO    Sexual Assault
2791    MacYesb          IO;#JI    Sexual Assault
2795   Delaware           H;#JI            Murder

                             List Add'l Crimes Recode  ...    *   FC  \
13                                   Rape;#Kidnapping  ...  NaN  NaN
15                                                NaN  ...  NaN  NaN
34                                                NaN  ...  NaN  NaN
37                                                NaN  ...    *  NaN
39    Gun Possession or Sale;#Illegal Use of a Weapon  ...  NaN  NaN
...                                               ...  ...  ...  ...
2768                              Robbery;#Kidnapping  ...  NaN  NaN
2789         Robbery;#Assault;#Kidnapping;#Conspiracy  ...  NaN  NaN
2790                    Assault;#Other Violent Felony  ...  NaN  NaN
2791                 Robbery;#Burglary/Unlawful Entry  ...  NaN  NaN
2795                        Rape;#Robbery;#Kidnapping  ...  NaN   FC

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
13                Yes           Yes     Yes                Yes  NaN
15                Yes           NaN     Yes                Yes  NaN
34                Yes           Yes     Yes                Yes  NaN
37                Yes           NaN     Yes                Yes  ILD
39                Yes           NaN     Yes                NaN  NaN
...               ...           ...     ...                ...  ...
2768              Yes           Yes     Yes                Yes  NaN
2789              Yes           NaN     Yes                Yes  ILD
2790              Yes           Yes     Yes                Yes  ILD
2791              Yes           NaN     Yes                Yes  NaN
2795              Yes           NaN     Yes                Yes  ILD

     Posting Date                Yes Tags Date of Crime Year
13        8/29/11  PR;#OF;#WH;#NW;#KP;#WT              1,978
15        8/29/11  PR;#OF;#WH;#NW;#KP;#WT              1,976
34        8/29/11  OF;#FA;#WH;#NW;#WT;#PJ              1,990
37         2/6/18          PR;#OF;#NW;#PJ              1,979
39        1/29/21                     NaN              2,011
...           ...                     ...                ...
2768      8/29/11      PR;#FA;#WH;#NW;#PJ              1,987
2789      10/2/18              OF;#NW;#WT              2,000
2790      8/30/12  PR;#OF;#WH;#NW;#WT;#PJ              1,980
2791      8/29/11  PR;#OF;#WH;#NW;#KP;#WT              1,994
2795      8/29/11      PR;#OF;#WH;#NW;#WT              1,981

[267 rows x 24 columns]
33.71212121212121

In [47]:
#mistaken witness and false evidence

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('MistakenWitness == "Yes" and FalseEvidence == "Yes"')

print(df1)

percent = (180/792) * 100

print(percent)

      Last Name    First Name   Age      Race   Sex          State  \
1         Abdal  Warith Habib  43.0     Black  Male       New York
13        Adams       Kenneth  21.0     Black  Male       Illinois
34    Alejandro       Gilbert  35.0  Hispanic  Male          Texas
38    Alexander       Richard  29.0     Black  Male        Indiana
53       Alonzo       Quintin  21.0  Hispanic  Male          Texas
...         ...           ...   ...       ...   ...            ...
2727   Williams        Willie  23.0     Black  Male        Georgia
2734     Willis          John  42.0     Black  Male       Illinois
2768    Woodall          Glen  28.0     White  Male  West Virginia
2771      Woods       Anthony  20.0     Black  Male       Missouri
2790      Wyatt   Rickey Dale  25.0     Black  Male          Texas

              County            Tags WorstCrimeDisplay  \
1               Erie              IO    Sexual Assault
13              Cook  CDC;#H;#IO;#JI            Murder
34            Uvalde             NaN    Sexual Assault
38        St. Joseph             NaN    Sexual Assault
53            Dallas          CIU;#H            Murder
...              ...             ...               ...
2727          Fulton              IO    Sexual Assault
2734            Cook             NaN    Sexual Assault
2768          Cabell             NaN    Sexual Assault
2771  St. Louis City              CV   Child Sex Abuse
2790          Dallas         CIU;#IO    Sexual Assault

                               List Add'l Crimes Recode  ...    *   FC  \
1                                               Robbery  ...  NaN  NaN
13                                     Rape;#Kidnapping  ...  NaN  NaN
34                                                  NaN  ...  NaN  NaN
38    Robbery;#Other Violent Felony;#Burglary/Unlawf...  ...  NaN  NaN
53                                              Assault  ...  NaN  NaN
...                                                 ...  ...  ...  ...
2727                                Assault;#Kidnapping  ...  NaN  NaN
2734                                            Robbery  ...  NaN  NaN
2768                                Robbery;#Kidnapping  ...  NaN  NaN
2771                               Other Violent Felony  ...  NaN  NaN
2790                      Assault;#Other Violent Felony  ...  NaN  NaN

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
1                 Yes           Yes     NaN                Yes  NaN
13                Yes           Yes     Yes                Yes  NaN
34                Yes           Yes     Yes                Yes  NaN
38                Yes           Yes     NaN                NaN  NaN
53                Yes           Yes     Yes                Yes  ILD
...               ...           ...     ...                ...  ...
2727              Yes           Yes     NaN                NaN  NaN
2734              Yes           Yes     Yes                Yes  NaN
2768              Yes           Yes     Yes                Yes  NaN
2771              Yes           Yes     NaN                NaN  NaN
2790              Yes           Yes     Yes                Yes  ILD

     Posting Date                        Yes Tags Date of Crime Year
1         8/29/11                  OF;#WH;#NW;#WT              1,982
13        8/29/11          PR;#OF;#WH;#NW;#KP;#WT              1,978
34        8/29/11          OF;#FA;#WH;#NW;#WT;#PJ              1,990
38        8/29/11                             NaN              1,996
53       11/11/19  PR;#OF;#WH;#NW;#KP;#WT;#PJ;#PL              2,001
...           ...                             ...                ...
2727      8/29/11                             NaN              1,985
2734      8/29/11              PR;#FA;#WH;#NW;#PJ              1,990
2768      8/29/11              PR;#FA;#WH;#NW;#PJ              1,987
2771      8/29/11                             NaN              1,983
2790      8/30/12          PR;#OF;#WH;#NW;#WT;#PJ              1,980

[180 rows x 24 columns]
22.727272727272727

In [49]:
#total insufficient legal defense

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

ILD = df["ILD"]
ILD_only = ILD.dropna()

total = ILD_only.value_counts()

print(total)


percent = (767/2809) * 100

print(percent)

ILD    767
Name: ILD, dtype: int64
27.30509077963688

In [59]:
#insufficient legal defense after 1989

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('ILD == "ILD" and Convicted > 1989')

#1989 was chosen as it entailed a massive upsurge in population - man mins created in 1986

print(df1)

percent = (624/767) * 100

print(percent)

            Last Name  First Name   Age             Race     Sex       State  \
4               Acero     Longino  35.0         Hispanic    Male  California
10              Adams  Jarrett M.  17.0            Black    Male   Wisconsin
21            Addison      Ronald  19.0            Black    Male    Maryland
24    Aguirre-Jarquin    Clemente  24.0         Hispanic    Male     Florida
25              Ahmed     Mubarez  31.0            Other    Male    Michigan
...               ...         ...   ...              ...     ...         ...
2780             Wosu         Joy  33.0            Black  Female    New York
2789        Wurdemann        John  29.0  Native American    Male       Idaho
2794         Yarbough     Anthony  18.0            Black    Male    New York
2803           Zapata     Rodrigo  25.0         Hispanic    Male       Texas
2807        Zimmerman        Evan  53.0            White    Male   Wisconsin

              County             Tags          WorstCrimeDisplay  \
4        Santa Clara            NC;#P  Sex Offender Registration
10         Jefferson           IO;#NC             Sexual Assault
21    Baltimore City            H;#IO                     Murder
24          Seminole            H;#IO                     Murder
25             Wayne       CIU;#H;#IO                     Murder
...              ...              ...                        ...
2780            Erie        CV;#F;#NC            Child Sex Abuse
2789          Canyon           A;#CDC           Attempted Murder
2794           Kings  CDC;#CIU;#CV;#H                     Murder
2803            Webb              NaN                    Robbery
2807      Eau Claire            H;#IO                     Murder

                      List Add'l Crimes Recode  ...    *   FC  \
4                                          NaN  ...  NaN  NaN
10                                         NaN  ...  NaN  NaN
21                      Gun Possession or Sale  ...  NaN  NaN
24                     Burglary/Unlawful Entry  ...  NaN  NaN
25                     Illegal Use of a Weapon  ...  NaN  NaN
...                                        ...  ...  ...  ...
2780                                       NaN  ...  NaN  NaN
2789  Robbery;#Assault;#Kidnapping;#Conspiracy  ...  NaN  NaN
2794                                       NaN  ...  NaN   FC
2803                                       NaN  ...  NaN  NaN
2807                                       NaN  ...    *   FC

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
4                 NaN           NaN     NaN                NaN  ILD
10                NaN           NaN     Yes                NaN  ILD
21                NaN           NaN     Yes                Yes  ILD
24                NaN           Yes     Yes                NaN  ILD
25                NaN           NaN     Yes                Yes  ILD
...               ...           ...     ...                ...  ...
2780              NaN           Yes     Yes                NaN  ILD
2789              Yes           NaN     Yes                Yes  ILD
2794              NaN           Yes     Yes                Yes  ILD
2803              Yes           NaN     NaN                Yes  ILD
2807              NaN           NaN     NaN                NaN  ILD

     Posting Date                 Yes Tags Date of Crime Year
4         8/29/11                      NaN              1,994
10        8/29/11                      NaN              1,998
21        8/29/11                   PR;#WH              1,996
24       11/11/18                      NaN              2,004
25       10/31/18       OF;#WH;#NW;#WT;#PJ              2,001
...           ...                      ...                ...
2780     12/18/13                      NaN              1,991
2789      10/2/18               OF;#NW;#WT              2,000
2794      2/11/14  OF;#WH;#NW;#WT;#INT;#PJ              1,992
2803      6/19/16                   PR;#WH              1,999
2807      8/29/11                      NaN              2,000

[624 rows x 24 columns]
81.35593220338984

In [70]:
#drug crimes and insufficient legal defense

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('ILD == "ILD" and WorstCrimeDisplay == "Drug Possession or Sale"')

print(df1)

percent = 22 / 767 * 100

print(percent)

       Last Name   First Name   Age             Race     Sex          State  \
149      Baltrip        Henry  22.0            Black    Male          Texas
191    Bell, Jr.        James  27.0            Black    Male   Pennsylvania
256        Bragg    Rodney L.  31.0            Black    Male       Arkansas
434   Chancellor       Darell  29.0            Black    Male       Michigan
526       Cortez       Arturo  34.0         Hispanic    Male     California
673        Dixon  Christopher  31.0            Black    Male          Texas
799         Fils       Roland  35.0            Black    Male  Massachusetts
955    Granberry      Roxanne  33.0            White  Female         Fed-VA
981        Gregg         Cody  26.0  Native American    Male      OklahYesa
1004      Guzman     Humberto  40.0         Hispanic    Male  Massachusetts
1104   Hernandez        Maria  39.0         Hispanic  Female         Fed-TX
1210     Jackson       Ieliot  26.0            Black    Male       Illinois
1211     Jackson         John  59.0            Black    Male     Washington
1314       Jones  Lydia Diane  40.0            Black  Female        Alabama
1452    Leverett          Ron  29.0            Black    Male        Georgia
1525      Magnan  Paul Philip  46.0            White    Male     California
1544      Maples        David  25.0            White    Male       Michigan
1729    Montilla       Carlos  22.0         Hispanic    Male  Massachusetts
2117   Rodriguez     Danielle  21.0         Hispanic  Female          Texas
2198      Sarber     Laurence  40.0            White    Male      Minnesota
2306       Smith         Eric  40.0            White    Male   Fed-Military
2732      Willis         Deon  33.0            Black    Male       Illinois

           County              Tags        WorstCrimeDisplay  \
149        Harris        CIU;#NC;#P  Drug Possession or Sale
191     Lancaster               NaN  Drug Possession or Sale
256         Clark               NaN  Drug Possession or Sale
434         Wayne               CIU  Drug Possession or Sale
526   Los Angeles               NaN  Drug Possession or Sale
673        Harris        CIU;#NC;#P  Drug Possession or Sale
799       Hampden               CDC  Drug Possession or Sale
955     (Eastern)       CDC;#FED;#F  Drug Possession or Sale
981     OklahYesa             NC;#P  Drug Possession or Sale
1004      Suffolk               NaN  Drug Possession or Sale
1104    (Western)            FED;#F  Drug Possession or Sale
1210         Cook               NaN  Drug Possession or Sale
1211        Grant               NaN  Drug Possession or Sale
1314    Jefferson                 F  Drug Possession or Sale
1452         Hart               NaN  Drug Possession or Sale
1525  Santa Clara               NaN  Drug Possession or Sale
1544      MacYesb                 P  Drug Possession or Sale
1729      Suffolk               NaN  Drug Possession or Sale
2117        Bexar  CIU;#F;#M;#NC;#P  Drug Possession or Sale
2198   Washington               NaN  Drug Possession or Sale
2306          NaN           FED;#NC  Drug Possession or Sale
2732         Cook    CIU;#IO;#NC;#P  Drug Possession or Sale

                      List Add'l Crimes Recode  ...    *   FC  \
149                                        NaN  ...  NaN  NaN
191                                Misdemeanor  ...  NaN  NaN
256                                        NaN  ...  NaN  NaN
434                                        NaN  ...  NaN  NaN
526                                        NaN  ...  NaN  NaN
673                                        NaN  ...  NaN  NaN
799                                        NaN  ...  NaN  NaN
955                                        NaN  ...  NaN  NaN
981                                        NaN  ...  NaN  NaN
1004                                       NaN  ...  NaN  NaN
1104                    Gun Possession or Sale  ...  NaN  NaN
1210                                       NaN  ...  NaN  NaN
1211                                       NaN  ...  NaN  NaN
1314                                       NaN  ...  NaN  NaN
1452                                       NaN  ...  NaN  NaN
1525  Traffic Offense;#Other Nonviolent Felony  ...  NaN  NaN
1544                                       NaN  ...  NaN  NaN
1729                    Gun Possession or Sale  ...  NaN  NaN
2117                               Misdemeanor  ...  NaN  NaN
2198                                       NaN  ...  NaN  NaN
2306                                       NaN  ...    *  NaN
2732                                       NaN  ...  NaN  NaN

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
149               NaN           Yes     NaN                NaN  ILD
191               NaN           NaN     Yes                Yes  ILD
256               NaN           NaN     Yes                Yes  ILD
434               NaN           NaN     Yes                Yes  ILD
526               NaN           NaN     Yes                Yes  ILD
673               NaN           Yes     NaN                Yes  ILD
799               NaN           NaN     Yes                NaN  ILD
955               NaN           NaN     Yes                NaN  ILD
981               NaN           Yes     NaN                NaN  ILD
1004              Yes           NaN     NaN                Yes  ILD
1104              NaN           NaN     NaN                NaN  ILD
1210              Yes           NaN     NaN                NaN  ILD
1211              NaN           NaN     Yes                Yes  ILD
1314              NaN           NaN     NaN                NaN  ILD
1452              Yes           NaN     NaN                NaN  ILD
1525              NaN           NaN     NaN                Yes  ILD
1544              NaN           NaN     NaN                NaN  ILD
1729              NaN           NaN     Yes                Yes  ILD
2117              NaN           NaN     NaN                NaN  ILD
2198              NaN           NaN     Yes                Yes  ILD
2306              NaN           Yes     NaN                NaN  ILD
2732              NaN           NaN     Yes                Yes  ILD

     Posting Date                Yes Tags Date of Crime Year
149        5/8/15                     NaN              2,013
191       6/18/14          OF;#WH;#NW;#PJ              2,007
256       8/29/11  PR;#OF;#WH;#NW;#KP;#PJ              1,993
434       5/18/20          OF;#WH;#NW;#PJ              2,011
526       2/16/14              OF;#NW;#PJ              1,998
673       9/18/17                  PR;#WH              2,005
799       10/4/16                     NaN              2,006
955       6/26/17                     NaN              2,015
981      10/18/19                     NaN              2,019
1004      8/29/11                  OF;#WH              1,990
1104      5/12/14                     NaN              2,001
1210     10/10/19                     NaN              2,009
1211      8/29/11      PR;#OF;#WH;#NW;#PJ              1,995
1314      8/24/14                     NaN              1,997
1452      8/29/11                     NaN              1,991
1525      8/29/11                  PR;#WH              1,999
1544      4/30/20                     NaN              1,993
1729      10/6/16          OF;#WH;#NW;#PJ              1,986
2117      3/26/20                     NaN              2,015
2198      9/11/19                  PR;#WH              2,004
2306      9/22/15                     NaN              2,011
2732      12/3/18              OF;#WH;#NW              2,008

[22 rows x 24 columns]
2.8683181225554106

In [68]:
#murder and insufficient legal defense

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('ILD == "ILD" and WorstCrimeDisplay == "Murder"')

print(df1)


percent = 355 / 767 * 100

print(percent)

            Last Name First Name   Age      Race   Sex          State  \
14              Adams   Laurence  19.0     Black  Male  Massachusetts
21            Addison     Ronald  19.0     Black  Male       Maryland
24    Aguirre-Jarquin   Clemente  24.0  Hispanic  Male        Florida
25              Ahmed    Mubarez  31.0     Other  Male       Michigan
29              Alcox       Joel  22.0     White  Male     California
...               ...        ...   ...       ...   ...            ...
2764          Woidtke     Rodney  27.0     White  Male       Illinois
2766             Wong      David  23.0     Asian  Male       New York
2794         Yarbough    Anthony  18.0     Black  Male       New York
2795           Yarris   Nicholas  20.0     White  Male   Pennsylvania
2807        Zimmerman       Evan  53.0     White  Male      Wisconsin

              County             Tags WorstCrimeDisplay  \
14           Suffolk            H;#JI            Murder
21    Baltimore City            H;#IO            Murder
24          Seminole            H;#IO            Murder
25             Wayne       CIU;#H;#IO            Murder
29     Santa Barbara                H            Murder
...              ...              ...               ...
2764       St. Clair                H            Murder
2766         Clinton            H;#JI            Murder
2794           Kings  CDC;#CIU;#CV;#H            Murder
2795        Delaware            H;#JI            Murder
2807      Eau Claire            H;#IO            Murder

              List Add'l Crimes Recode  ...    *   FC  MistakenWitness  \
14                             Robbery  ...  NaN  NaN              NaN
21              Gun Possession or Sale  ...  NaN  NaN              NaN
24             Burglary/Unlawful Entry  ...  NaN  NaN              NaN
25             Illegal Use of a Weapon  ...  NaN  NaN              NaN
29    Robbery;#Burglary/Unlawful Entry  ...  NaN   FC              NaN
...                                ...  ...  ...  ...              ...
2764                              Rape  ...  NaN   FC              NaN
2766                               NaN  ...  NaN  NaN              NaN
2794                               NaN  ...  NaN   FC              NaN
2795         Rape;#Robbery;#Kidnapping  ...  NaN   FC              Yes
2807                               NaN  ...    *   FC              NaN

     FalseEvidence Perjury OfficialMisconduct  ILD Posting Date  \
14             NaN     Yes                Yes  ILD      8/29/11
21             NaN     Yes                Yes  ILD      8/29/11
24             Yes     Yes                NaN  ILD     11/11/18
25             NaN     Yes                Yes  ILD     10/31/18
29             NaN     Yes                Yes  ILD      5/31/16
...            ...     ...                ...  ...          ...
2764           NaN     NaN                Yes  ILD      8/29/11
2766           NaN     Yes                NaN  ILD      8/29/11
2794           Yes     Yes                Yes  ILD      2/11/14
2795           NaN     Yes                Yes  ILD      8/29/11
2807           NaN     NaN                NaN  ILD      8/29/11

                     Yes Tags Date of Crime Year
14         PR;#WH;#NW;#KP;#WT              1,972
21                     PR;#WH              1,996
24                        NaN              2,004
25         OF;#WH;#NW;#WT;#PJ              2,001
29     PR;#OF;#WH;#NW;#WT;#PL              1,986
...                       ...                ...
2764                   PR;#WH              1,988
2766                      NaN              1,986
2794  OF;#WH;#NW;#WT;#INT;#PJ              1,992
2795       PR;#OF;#WH;#NW;#WT              1,981
2807                      NaN              2,000

[355 rows x 24 columns]
46.28422425032595

In [71]:
#sexual assault and insufficient legal defense

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('ILD == "ILD" and WorstCrimeDisplay == "Sexual Assault"')

print(df1)

percent = 61 / 767 * 100

print(percent)

      Last Name   First Name   Age      Race   Sex           State  \
10        Adams   Jarrett M.  17.0     Black  Male       Wisconsin
37    Alexander      Malcolm  19.0     Black  Male       Louisiana
54     Alowonle       Rilwan  50.0     Black  Male       Minnesota
119      Aviles      Anselmo  22.0  Hispanic  Male   Massachusetts
177      Baylor       Ronnie  25.0     Black  Male      California
...         ...          ...   ...       ...   ...             ...
2587     Walker       Joseph  44.0     Black  Male  South Carolina
2598      Walls       George  39.0     Black  Male    Pennsylvania
2679    Wickham  Christopher  27.0     White  Male            Utah
2690  Wilkerson         Mike  39.0     White  Male        Missouri
2790      Wyatt  Rickey Dale  25.0     Black  Male           Texas

          County     Tags WorstCrimeDisplay  \
10     Jefferson   IO;#NC    Sexual Assault
37     Jefferson       IO    Sexual Assault
54    Washington       NC    Sexual Assault
119    Worcester      NaN    Sexual Assault
177    Riverside      NaN    Sexual Assault
...          ...      ...               ...
2587     Bamberg      NaN    Sexual Assault
2598   Allegheny       NC    Sexual Assault
2679  Salt Lake    CV;#IO    Sexual Assault
2690      Jasper    CV;#P    Sexual Assault
2790      Dallas  CIU;#IO    Sexual Assault

                               List Add'l Crimes Recode  ...    *   FC  \
10                                                  NaN  ...  NaN  NaN
37                                                  NaN  ...    *  NaN
54                                                  NaN  ...  NaN  NaN
119                    Assault;#Burglary/Unlawful Entry  ...  NaN  NaN
177   Robbery;#Burglary/Unlawful Entry;#Theft;#Illeg...  ...  NaN   FC
...                                                 ...  ...  ...  ...
2587                                         Kidnapping  ...  NaN  NaN
2598                                                NaN  ...  NaN  NaN
2679                                                NaN  ...  NaN  NaN
2690  Assault;#Burglary/Unlawful Entry;#Illegal Use ...  ...    *   FC
2790                      Assault;#Other Violent Felony  ...  NaN  NaN

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
10                NaN           NaN     Yes                NaN  ILD
37                Yes           NaN     Yes                Yes  ILD
54                NaN           NaN     Yes                NaN  ILD
119               Yes           NaN     NaN                NaN  ILD
177               NaN           NaN     NaN                Yes  ILD
...               ...           ...     ...                ...  ...
2587              Yes           NaN     NaN                NaN  ILD
2598              NaN           NaN     Yes                NaN  ILD
2679              Yes           NaN     NaN                Yes  ILD
2690              Yes           NaN     NaN                Yes  ILD
2790              Yes           Yes     Yes                Yes  ILD

     Posting Date                Yes Tags Date of Crime Year
10        8/29/11                     NaN              1,998
37         2/6/18          PR;#OF;#NW;#PJ              1,979
54        3/10/14                     NaN              2,006
119        9/4/12                     NaN              1,988
177       2/26/14         OF;#WH;#NW;#INT              1,987
...           ...                     ...                ...
2587     11/25/14                     NaN              2,002
2598      8/30/12                     NaN              2,002
2679      10/2/19                  PR;#WH              1,995
2690       7/5/17                  OF;#NW              1,997
2790      8/30/12  PR;#OF;#WH;#NW;#WT;#PJ              1,980

[61 rows x 24 columns]
7.953063885267275

In [12]:
#false confessions and insufficient legal defense

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('FC == "FC" and ILD == "ILD"')

print(df1)

percent = 106 / 344 * 100

print(percent)

      Last Name First Name   Age   Race   Sex         State         County  \
22        Agnew    Gregory  28.0  Black  Male      Illinois           Lake
29        Alcox       Joel  22.0  White  Male    California  Santa Barbara
138       Baker     Edward  17.0  Black  Male  Pennsylvania   Philadelphia
177      Baylor     Ronnie  25.0  Black  Male    California      Riverside
189        Bell     George  19.0  Black  Male      New York         Queens
...         ...        ...   ...    ...   ...           ...            ...
2751     Wilson    Sharrif  15.0  Black  Male      New York          Kings
2764    Woidtke     Rodney  27.0  White  Male      Illinois      St. Clair
2794   Yarbough    Anthony  18.0  Black  Male      New York          Kings
2795     Yarris   Nicholas  20.0  White  Male  Pennsylvania       Delaware
2807  Zimmerman       Evan  53.0  White  Male     Wisconsin     Eau Claire

                 Tags WorstCrimeDisplay  \
22                 NC           Robbery
29                  H            Murder
138        CDC;#H;#IO            Murder
177               NaN    Sexual Assault
189   CDC;#CIU;#H;#JI            Murder
...               ...               ...
2751  CDC;#CIU;#CV;#H            Murder
2764                H            Murder
2794  CDC;#CIU;#CV;#H            Murder
2795            H;#JI            Murder
2807            H;#IO            Murder

                               List Add'l Crimes Recode  ... MistakenWitness  \
22                                                  NaN  ...             NaN
29                     Robbery;#Burglary/Unlawful Entry  ...             NaN
138        Robbery;#Burglary/Unlawful Entry;#Conspiracy  ...             NaN
177   Robbery;#Burglary/Unlawful Entry;#Theft;#Illeg...  ...             NaN
189   Attempt, Violent;#Burglary/Unlawful Entry;#Gun...  ...             Yes
...                                                 ...  ...             ...
2751                                                NaN  ...             NaN
2764                                               Rape  ...             NaN
2794                                                NaN  ...             NaN
2795                          Rape;#Robbery;#Kidnapping  ...             Yes
2807                                                NaN  ...             NaN

      FalseEvidence  Perjury OfficialMisconduct  ILD Posting Date  \
22              NaN      Yes                NaN  ILD      1/18/18
29              NaN      Yes                Yes  ILD      5/31/16
138             NaN      Yes                Yes  ILD      8/29/11
177             NaN      NaN                Yes  ILD      2/26/14
189             NaN      Yes                Yes  ILD      6/13/21
...             ...      ...                ...  ...          ...
2751            Yes      Yes                Yes  ILD      2/11/14
2764            NaN      NaN                Yes  ILD      8/29/11
2794            Yes      Yes                Yes  ILD      2/11/14
2795            NaN      Yes                Yes  ILD      8/29/11
2807            NaN      NaN                NaN  ILD      8/29/11

                     Yes Tags Date of Crime Year Unnamed: 24  CIU
22                        NaN              1,988         NaN  NaN
29     PR;#OF;#WH;#NW;#WT;#PL              1,986         NaN  NaN
138           OF;#WH;#NW;#INT              1,973         NaN  NaN
177           OF;#WH;#NW;#INT              1,987         NaN  NaN
189   PR;#OF;#WH;#NW;#WT;#INT              1,996         NaN  NaN
...                       ...                ...         ...  ...
2751      OF;#NW;#WT;#INT;#PJ              1,992         NaN  NaN
2764                   PR;#WH              1,988         NaN  NaN
2794  OF;#WH;#NW;#WT;#INT;#PJ              1,992         NaN  NaN
2795       PR;#OF;#WH;#NW;#WT              1,981         NaN  NaN
2807                      NaN              2,000         NaN  NaN

[106 rows x 26 columns]
30.813953488372093

In [11]:
#total number of false confessions

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

FC = df["FC"]
FC_only = FC.dropna()

total = FC_only.value_counts()

print(total)

FC    344
Name: FC, dtype: int64

In [81]:
#total number of official misconduct

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

FC = df["OfficialMisconduct"]
FC_only = FC.dropna()

total = FC_only.value_counts()

print(total)

Yes    1552
Name: OfficialMisconduct, dtype: int64

In [82]:
#age stats

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df.describe()

               Age    Convicted   Exonerated
count  2800.000000  2810.000000  2810.000000
mean     28.557500  1997.899288  2009.220285
std      10.224398    10.988950     8.611232
min      11.000000  1956.000000  1989.000000
25%      20.000000  1990.000000  2002.000000
50%      26.000000  1997.000000  2012.000000
75%      35.000000  2007.000000  2016.000000
max      83.000000  2020.000000  2021.000000

In [92]:
#total count per state

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

pd.set_option('display.max_rows', 500)

FC = df["State"]

total = FC.value_counts()

print(total)


texas = 392/2809 * 100

il = 351/2809 * 100

ny = 290/2809 * 100

ca = 233/2809 * 100

mi = 134/2809 * 100

Texas                   392
Illinois                351
New York                290
California              233
Michigan                134
Pennsylvania             98
Ohio                     85
Massachusetts            77
Florida                  76
North Carolina           66
Louisiana                63
Wisconsin                59
Virginia                 56
Washington               50
Missouri                 50
Georgia                  44
New Jersey               42
Maryland                 40
Indiana                  38
OklahYesa                38
Connecticut              29
Alabama                  27
Tennessee                24
Mississippi              23
Arizona                  22
Oregon                   22
Kentucky                 22
Fed-NY                   21
Nevada                   20
District of Columbia     19
Utah                     18
Minnesota                17
Iowa                     16
Montana                  14
Kansas                   14
Fed-CA                   13
Arkansas                 12
West Virginia            11
Colorado                 11
New Mexico               10
South Carolina            9
Nebraska                  9
Alaska                    8
Fed-TN                    6
Fed-LA                    6
Puerto Rico               6
Rhode Island              6
Fed-Military              6
Idaho                     6
Fed-IL                    6
Fed-FL                    6
Fed-WI                    5
South Dakota              5
Fed-MD                    5
Hawaii                    5
Fed-PA                    5
Fed-TX                    5
Fed-VA                    5
WyYesing                  4
Fed-DC                    4
Fed-MO                    4
North Dakota              4
Maine                     4
Fed-AZ                    3
Fed-MA                    3
Delaware                  3
Fed-MI                    3
Vermont                   3
Fed-OH                    2
Fed-WA                    2
New Hampshire             2
Fed-CT                    2
Guam                      2
Fed-MT                    1
Fed-NM                    1
Fed-ND                    1
Fed-NV                    1
Fed-AL                    1
Fed-KY                    1
Fed-SD                    1
Fed-MN                    1
Fed-NJ                    1
Name: State, dtype: int64

In [93]:
#total count per collumn

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df.count()

Last Name                   2810
First Name                  2810
Age                         2800
Race                        2810
Sex                         2810
State                       2810
County                      2759
Tags                        2532
WorstCrimeDisplay           2810
List Add'l Crimes Recode    1141
Sentence                    2810
Convicted                   2810
Exonerated                  2810
DNA                          540
*                            163
FC                           344
MistakenWitness              792
FalseEvidence                681
Perjury                     1695
OfficialMisconduct          1552
ILD                          767
Posting Date                2810
Yes Tags                    1552
Date of Crime Year          2810
dtype: int64

In [7]:
#within texas analysis

per_capita_exoneration = (392 * 100000) / 29000000


df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('State == "Texas"')

percent = 70/392 * 100

#197 Texas CIU and 392 total CIU

percent2 = 197/392 *100

#46 Texas + IO and 392 total IO

percent3 = 46/392 *100

print(df1)

print(percent)

print(percent2)

print(percent3)

print(per_capita_exoneration)

          Last Name    First Name   Age      Race     Sex  State  County  \
7             Adams       Darryl   25.0     Black    Male  Texas  Dallas
12            Adams        Johnny  52.0     Black    Male  Texas  Harris
15            Adams  Randall Dale  28.0     White    Male  Texas  Dallas
28        Albritton           Amy  43.0     White  Female  Texas  Harris
30    Aldape Guerra      Ricardo   20.0  Hispanic    Male  Texas  Harris
...             ...           ...   ...       ...     ...    ...     ...
2790          Wyatt   Rickey Dale  25.0     Black    Male  Texas  Dallas
2793     Yac-Garcia          Jose  27.0  Hispanic    Male  Texas  Harris
2801        Yurtman         Ersan  18.0  Hispanic    Male  Texas   Bexar
2803         Zapata       Rodrigo  25.0  Hispanic    Male  Texas    Webb
2804        Zarzoza      Jonathan  18.0     White    Male  Texas  Harris

                  Tags      Worst Crime Display  \
7       CIU;#IO;#NC;#P           Sexual Assault
12          CIU;#NC;#P  Drug Possession or Sale
15              CDC;#H                   Murder
28       CIU;#F;#NC;#P  Drug Possession or Sale
30                   H                   Murder
...                ...                      ...
2790           CIU;#IO           Sexual Assault
2793        CIU;#NC;#P  Drug Possession or Sale
2801  CDC;#CIU;#CV;#IO          Child Sex Abuse
2803               NaN                  Robbery
2804             NC;#P  Drug Possession or Sale

           List Add'l Crimes Recode  ...    *   FC  MWID  F/MFE  P/FA   OM  \
7                               NaN  ...    *  NaN   NaN    NaN  P/FA  NaN
12                              NaN  ...  NaN  NaN   NaN  F/MFE   NaN  NaN
15                              NaN  ...  NaN  NaN  MWID    NaN  P/FA   OM
28                              NaN  ...  NaN  NaN   NaN  F/MFE   NaN  NaN
30                              NaN  ...  NaN  NaN   NaN    NaN  P/FA   OM
...                             ...  ...  ...  ...   ...    ...   ...  ...
2790  Assault;#Other Violent Felony  ...  NaN  NaN  MWID  F/MFE  P/FA   OM
2793                            NaN  ...  NaN  NaN   NaN  F/MFE   NaN  NaN
2801                            NaN  ...    *  NaN   NaN    NaN  P/FA   OM
2803                            NaN  ...  NaN  NaN  MWID    NaN   NaN   OM
2804                            NaN  ...  NaN  NaN   NaN  F/MFE   NaN  NaN

      ILD Posting Date                     OM Tags Date of Crime Year
7     NaN      2/18/17                         NaN              1,992
12    NaN      3/18/16                         NaN              2,008
15    NaN      8/29/11      PR;#OF;#WH;#NW;#KP;#WT              1,976
28    NaN      7/22/16                         NaN              2,010
30    NaN      8/29/11  PR;#OF;#WH;#NW;#KP;#WT;#PL              1,982
...   ...          ...                         ...                ...
2790  ILD      8/30/12      PR;#OF;#WH;#NW;#WT;#PJ              1,980
2793  NaN      11/3/15                         NaN              2,015
2801  NaN      8/10/20          PR;#OF;#WH;#NW;#WT              1,992
2803  ILD      6/19/16                      PR;#WH              1,999
2804  NaN      6/16/20                         NaN              2,013

[392 rows x 24 columns]
17.857142857142858
50.255102040816325
11.73469387755102
1.3517241379310345

In [116]:
#illinois analysis

per_capita_exoneration = (351 * 100000) / 12670000


df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('State == "Illinois" and DNA == "DNA"')

percent = 63/540 * 100

#127 Ill + CIU and 500 total CIU

percent2 = 127/500 *100

#171 Ill + IO and 447 total IO

percent3 = 171/447 *100

print(df1)

print(percent)

print(percent2)

print(percent3)

print(per_capita_exoneration)

         Last Name   First Name   Age      Race     Sex     State     County  \
2        Abernathy  Christopher  17.0     White    Male  Illinois       Cook
13           Adams      Kenneth  21.0     Black    Male  Illinois       Cook
69        Andersen       Daniel  19.0     White    Male  Illinois       Cook
129         Bailey        Kevin  19.0     Black    Male  Illinois       Cook
163           Barr     Jonathan  14.0     Black    Male  Illinois       Cook
170      Batchelor        Corey  19.0     Black    Male  Illinois       Cook
249       Bradford   Marcellius  17.0     Black    Male  Illinois       Cook
283    Brooks, Jr.       Claude  35.0     Black    Male  Illinois       Cook
320        Bullock       Ronnie  27.0     Black    Male  Illinois       Cook
358           Cage        Dean   28.0     Black    Male  Illinois       Cook
388         Carini      William  28.0     White    Male  Illinois       Lake
496        Coleman       Nevest  25.0     Black    Male  Illinois       Cook
569           Cruz      Rolando  19.0  Hispanic    Male  Illinois     DuPage
605          Davis        Andre  19.0     Black    Male  Illinois  Champaign
685     DYesinguez    Alejandro  16.0  Hispanic    Male  Illinois       Lake
692         Dotson         Gary  20.0     White    Male  Illinois       Cook
732        Edwards        James  44.0     Black    Male  Illinois       Lake
766          Evans      Michael  17.0     Black    Male  Illinois       Cook
845         Fulton       Darryl  26.0     Black    Male  Illinois       Cook
846         Fulton         John  18.0     Black    Male  Illinois       Cook
893   Geralds, Jr.       Hubert  30.0     Black    Male  Illinois       Cook
903        Gillard        Larry  22.0     Black    Male  Illinois       Cook
934       Gonzalez        Angel  20.0  Hispanic    Male  Illinois       Lake
964           Gray    David A.   25.0     Black    Male  Illinois    Madison
965           Gray        Paula  17.0     Black  Female  Illinois       Cook
1038        Harden        James  16.0     Black    Male  Illinois       Cook
1099     Hernandez    Alejandro  19.0  Hispanic    Male  Illinois     DuPage
1123          Hill       Harold  16.0     Black    Male  Illinois       Cook
1143       Holland         Dana  25.0     Black    Male  Illinois       Cook
1144       Holland         Dana  25.0     Black    Male  Illinois       Cook
1251      Jimerson      Verneal  25.0     Black    Male  Illinois       Cook
1285       Johnson      Richard  31.0     Black    Male  Illinois       Cook
1322         Jones       Ronald  34.0     Black    Male  Illinois       Cook
1478      Linscott       Steven  26.0     White    Male  Illinois       Cook
1517         Lyons       Marcus  29.0     Black    Male  Illinois     DuPage
1581        Maxson         Mark  31.0     Black    Male  Illinois       Cook
1686        Miller        Jerry  23.0     Black    Male  Illinois       Cook
1706      Mitchell      Anthony  17.0     Black    Male  Illinois       Cook
1787          Nash   Alprentiss  20.0     Black    Male  Illinois       Cook
1844        Ollins       Calvin  14.0     Black    Male  Illinois       Cook
1845        Ollins        Larry  16.0     Black    Male  Illinois       Cook
1881        Palmer      Charles  43.0     Black    Male  Illinois      Macon
1906    Pattersonï¿½      Maurice  35.0     Black    Male  Illinois       Cook
1925     Pendleton       Marlon  35.0     Black    Male  Illinois       Cook
2027        Rainge       Willie  20.0     Black    Male  Illinois       Cook
2065      Reynolds       Donald  20.0     Black    Male  Illinois       Cook
2070    Richardson       Harold  16.0     Black    Male  Illinois       Cook
2085       Rivera          Juan  19.0  Hispanic    Male  Illinois       Lake
2135       Rollins      Lafonso  17.0     Black    Male  Illinois       Cook
2202      Saunders      Michael  15.0     Black    Male  Illinois       Cook
2203      Saunders        Yesar  18.0     Black    Male  Illinois       Cook
2204        Savory      Johnnie  14.0     Black    Male  Illinois     Peoria
2242         Sharp      Shainne  16.0     Black    Male  Illinois       Cook
2353        Starks       Bennie  26.0     Black    Male  Illinois       Lake
2406         Swift      Terrill  17.0     Black    Male  Illinois       Cook
2429        Taylor       Robert  14.0     Black    Male  Illinois       Cook
2437         Terry         Paul  17.0     Black    Male  Illinois       Cook
2440        Thames      Vincent  17.0     Black    Male  Illinois       Cook
2554          Veal       Robert  14.0     Black    Male  Illinois       Cook
2605       Wardell        Billy  21.0     Black    Male  Illinois       Cook
2704      Williams       Dennis  21.0     Black    Male  Illinois       Cook
2734        Willis         John  42.0     Black    Male  Illinois       Cook
2799    Young, Jr.          Dan  30.0     Black    Male  Illinois       Cook

                 Tags WorstCrimeDisplay  \
2      CIU;#CV;#H;#IO            Murder
13     CDC;#H;#IO;#JI            Murder
69              H;#IO            Murder
129        CDC;#H;#IO            Murder
163    CDC;#CV;#H;#IO            Murder
170        CDC;#H;#IO            Murder
249            CDC;#P        Kidnapping
283                CV   Child Sex Abuse
320                CV   Child Sex Abuse
358            CV;#IO   Child Sex Abuse
388               CIU    Sexual Assault
496   CDC;#CIU;#H;#IO            Murder
569    CDC;#CV;#H;#JI            Murder
605         CV;#H;#IO            Murder
685               NaN    Sexual Assault
692            CV;#NC    Sexual Assault
732                 H            Murder
766         CV;#H;#IO            Murder
845       CDC;#CIU;#H            Murder
846            CDC;#H            Murder
893                 H            Murder
903                IO    Sexual Assault
934           CIU;#IO    Sexual Assault
964                JI  Attempted Murder
965          F;#H;#JI            Murder
1038       CDC;#CV;#H            Murder
1099   CDC;#CV;#H;#JI            Murder
1123        A;#CDC;#H            Murder
1143               IO    Sexual Assault
1144               IO  Attempted Murder
1251   CDC;#H;#IO;#JI            Murder
1285              NaN    Sexual Assault
1322                H            Murder
1478                H            Murder
1517              NaN    Sexual Assault
1581       CIU;#CV;#H            Murder
1686               IO    Sexual Assault
1706           CDC;#H            Murder
1787      CDC;#CIU;#H            Murder
1844           CDC;#H            Murder
1845           CDC;#H            Murder
1881            H;#IO            Murder
1906            H;#IO            Murder
1925               IO    Sexual Assault
2027   CDC;#H;#IO;#JI            Murder
2065              NaN    Sexual Assault
2070           CDC;#H            Murder
2085    CV;#H;#IO;#JI            Murder
2135              NaN    Sexual Assault
2202           CDC;#H            Murder
2203           CDC;#H            Murder
2204        CV;#H;#IO            Murder
2242    CDC;#CV;#H;#P            Murder
2353               IO    Sexual Assault
2406           CDC;#H            Murder
2429       CDC;#CV;#H            Murder
2437        CV;#H;#IO            Murder
2440        CDC;#H;#P            Murder
2554    CDC;#CV;#H;#P            Murder
2605              NaN    Sexual Assault
2704   CDC;#H;#IO;#JI            Murder
2734              NaN    Sexual Assault
2799        A;#CDC;#H            Murder

                               List Add'l Crimes Recode  ...    *   FC  \
2                                         Rape;#Robbery  ...  NaN   FC
13                                     Rape;#Kidnapping  ...  NaN  NaN
69                                     Attempt, Violent  ...    *   FC
129                    Robbery;#Burglary/Unlawful Entry  ...    *   FC
163                                                Rape  ...  NaN  NaN
170                    Robbery;#Burglary/Unlawful Entry  ...    *   FC
249                                                 NaN  ...  NaN   FC
283                                                 NaN  ...    *  NaN
320                                          Kidnapping  ...  NaN  NaN
358                                                 NaN  ...  NaN  NaN
388                                                 NaN  ...    *  NaN
496                                    Rape;#Kidnapping  ...  NaN   FC
569           Rape;#Kidnapping;#Burglary/Unlawful Entry  ...  NaN   FC
605                         Child Sex Abuse;#Kidnapping  ...    *  NaN
685                             Burglary/Unlawful Entry  ...  NaN  NaN
692                                          Kidnapping  ...  NaN  NaN
732                                             Robbery  ...  NaN   FC
766                                    Rape;#Kidnapping  ...  NaN   FC
845                                                Rape  ...  NaN   FC
846                 Kidnapping;#Other Nonviolent Felony  ...    *   FC
893                                                Rape  ...    *   FC
903                                             Robbery  ...  NaN  NaN
934                                          Kidnapping  ...  NaN   FC
964                                       Rape;#Robbery  ...  NaN  NaN
965                                       Rape;#Perjury  ...  NaN   FC
1038                                               Rape  ...  NaN  NaN
1099          Rape;#Kidnapping;#Burglary/Unlawful Entry  ...  NaN   FC
1123                  Sexual Assault;#Arson;#Kidnapping  ...    *   FC
1143                                                NaN  ...  NaN  NaN
1144                                            Robbery  ...    *  NaN
1251                                               Rape  ...  NaN  NaN
1285       Robbery;#Kidnapping;#Burglary/Unlawful Entry  ...  NaN  NaN
1322                                               Rape  ...  NaN   FC
1478                                                NaN  ...  NaN   FC
1517                               Other Violent Felony  ...  NaN  NaN
1581                                               Rape  ...  NaN   FC
1686                                Robbery;#Kidnapping  ...  NaN  NaN
1706                Kidnapping;#Other Nonviolent Felony  ...    *   FC
1787  Robbery;#Attempt, Violent;#Burglary/Unlawful E...  ...    *  NaN
1844                                   Rape;#Kidnapping  ...  NaN   FC
1845                          Rape;#Robbery;#Kidnapping  ...  NaN  NaN
1881                                                NaN  ...    *  NaN
1906                                                NaN  ...  NaN  NaN
1925                                            Robbery  ...  NaN  NaN
2027                                               Rape  ...  NaN  NaN
2065                                            Robbery  ...  NaN  NaN
2070                                               Rape  ...  NaN   FC
2085                                                NaN  ...  NaN   FC
2135                                            Robbery  ...  NaN   FC
2202                                               Rape  ...  NaN   FC
2203                          Rape;#Robbery;#Kidnapping  ...  NaN  NaN
2204                                                NaN  ...    *   FC
2242                                               Rape  ...  NaN   FC
2353                          Assault;#Attempt, Violent  ...  NaN  NaN
2406                                               Rape  ...  NaN   FC
2429                                               Rape  ...  NaN   FC
2437                                   Rape;#Kidnapping  ...  NaN  NaN
2440                                               Rape  ...  NaN   FC
2554                                               Rape  ...  NaN   FC
2605                                            Robbery  ...  NaN  NaN
2704                         Sexual Assault;#Kidnapping  ...  NaN  NaN
2734                                            Robbery  ...  NaN  NaN
2799                  Sexual Assault;#Arson;#Kidnapping  ...    *   FC

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
2                 NaN           NaN     Yes                Yes  NaN
13                Yes           Yes     Yes                Yes  NaN
69                NaN           NaN     Yes                Yes  NaN
129               NaN           NaN     Yes                Yes  NaN
163               NaN           NaN     Yes                Yes  NaN
170               NaN           NaN     Yes                Yes  NaN
249               NaN           Yes     Yes                Yes  NaN
283               NaN           NaN     Yes                NaN  NaN
320               Yes           NaN     NaN                NaN  NaN
358               Yes           NaN     NaN                NaN  NaN
388               Yes           NaN     NaN                NaN  NaN
496               NaN           NaN     Yes                Yes  NaN
569               NaN           Yes     Yes                Yes  NaN
605               NaN           Yes     Yes                NaN  NaN
685               Yes           Yes     NaN                Yes  NaN
692               NaN           Yes     Yes                Yes  NaN
732               NaN           NaN     Yes                Yes  NaN
766               Yes           NaN     NaN                Yes  NaN
845               NaN           NaN     Yes                Yes  NaN
846               NaN           NaN     Yes                Yes  ILD
893               NaN           NaN     NaN                NaN  NaN
903               Yes           Yes     NaN                Yes  NaN
934               Yes           NaN     NaN                Yes  NaN
964               Yes           Yes     Yes                Yes  NaN
965               Yes           Yes     Yes                Yes  NaN
1038              NaN           NaN     Yes                Yes  NaN
1099              NaN           Yes     Yes                Yes  NaN
1123              NaN           Yes     Yes                Yes  NaN
1143              Yes           Yes     Yes                Yes  NaN
1144              NaN           NaN     Yes                NaN  NaN
1251              Yes           Yes     Yes                Yes  NaN
1285              Yes           NaN     NaN                NaN  ILD
1322              Yes           Yes     NaN                Yes  NaN
1478              NaN           Yes     NaN                Yes  NaN
1517              Yes           NaN     NaN                Yes  NaN
1581              NaN           NaN     Yes                Yes  NaN
1686              Yes           NaN     NaN                Yes  NaN
1706              NaN           NaN     Yes                Yes  ILD
1787              Yes           NaN     Yes                NaN  NaN
1844              NaN           Yes     Yes                Yes  NaN
1845              NaN           Yes     Yes                Yes  NaN
1881              NaN           Yes     Yes                NaN  NaN
1906              Yes           Yes     Yes                Yes  NaN
1925              Yes           Yes     Yes                Yes  NaN
2027              Yes           Yes     Yes                Yes  ILD
2065              Yes           Yes     Yes                Yes  NaN
2070              NaN           NaN     Yes                Yes  NaN
2085              Yes           Yes     Yes                Yes  NaN
2135              Yes           Yes     NaN                Yes  ILD
2202              NaN           NaN     Yes                Yes  NaN
2203              NaN           Yes     Yes                Yes  NaN
2204              NaN           NaN     Yes                Yes  ILD
2242              NaN           NaN     Yes                Yes  NaN
2353              NaN           Yes     Yes                Yes  NaN
2406              NaN           NaN     Yes                NaN  NaN
2429              NaN           NaN     Yes                Yes  NaN
2437              Yes           NaN     NaN                Yes  NaN
2440              NaN           NaN     Yes                Yes  NaN
2554              NaN           NaN     Yes                Yes  NaN
2605              Yes           Yes     Yes                Yes  NaN
2704              Yes           Yes     Yes                Yes  ILD
2734              Yes           Yes     Yes                Yes  NaN
2799              NaN           Yes     Yes                Yes  NaN

     Posting Date                             Yes Tags Date of Crime Year
2         2/13/15                      OF;#WH;#NW;#INT              1,984
13        8/29/11               PR;#OF;#WH;#NW;#KP;#WT              1,978
69        8/15/15                  OF;#WH;#NW;#INT;#PJ              1,980
129        2/3/18                  OF;#WH;#NW;#INT;#PJ              1,989
163       1/23/12                       OF;#WH;#NW;#WT              1,991
170        2/3/18                      OF;#WH;#NW;#INT              1,989
249       8/29/11                      OF;#FA;#NW;#INT              1,986
283       6/20/17                                  NaN              1,997
320       8/29/11                                  NaN              1,983
358       8/29/11                                  NaN              1,994
388       1/10/17                                  NaN              1,991
496       12/4/17                  OF;#WH;#NW;#PJ;#INT              1,994
569       8/29/11               PR;#OF;#FA;#WH;#NW;#PJ              1,983
605        7/6/12                                  NaN              1,980
685       8/29/11                               OF;#WH              1,989
692       8/29/11                       FA;#WH;#NW;#PJ              1,977
732       6/10/12                  OF;#WH;#NW;#PJ;#INT              1,994
766       8/29/11                       PR;#OF;#WH;#NW              1,976
845       12/4/17                  OF;#WH;#NW;#PJ;#INT              1,994
846       6/17/20  PR;#OF;#WH;#NW;#KP;#WT;#INT;#PJ;#PL              2,003
893       8/31/11                                  NaN              1,994
903       8/29/11                               FA;#WH              1,981
934       3/12/15                          OF;#NW;#INT              1,994
964       8/29/11                               PR;#NW              1,978
965       8/29/11          PR;#OF;#WH;#NW;#KP;#WT;#INT              1,978
1038      1/23/12                       OF;#WH;#NW;#WT              1,991
1099      8/29/11          PR;#OF;#FA;#WH;#NW;#INT;#PJ              1,983
1123      8/29/11                      OF;#NW;#WT;#INT              1,990
1143      8/29/11                           FA;#WH;#NW              1,993
1144      8/29/11                                  NaN              1,993
1251      8/29/11               PR;#OF;#WH;#NW;#KP;#WT              1,978
1285      8/29/11                                  NaN              1,990
1322      8/29/11                      OF;#WH;#NW;#INT              1,985
1478      8/29/11                           PR;#NW;#PL              1,980
1517      8/29/11               PR;#OF;#WH;#NW;#WT;#PL              1,987
1581      10/2/16                  OF;#WH;#NW;#INT;#PJ              1,992
1686      8/29/11                           FA;#WH;#NW              1,981
1706      6/17/20  PR;#OF;#WH;#NW;#KP;#WT;#INT;#PJ;#PL              2,003
1787      8/30/12                                  NaN              1,995
1844      8/29/11               OF;#FA;#WH;#NW;#WT;#PJ              1,986
1845      8/29/11               OF;#FA;#WH;#NW;#WT;#PJ              1,986
1881      12/4/16                                  NaN              1,998
1906      8/29/11           PR;#OF;#WH;#NW;#KP;#PJ;#PL              2,002
1925      8/29/11                   OF;#FA;#WH;#NW;#WT              1,992
2027      8/29/11               PR;#OF;#WH;#NW;#KP;#WT              1,978
2065      8/29/11                       FA;#WH;#NW;#PJ              1,986
2070      1/27/12                      OF;#WH;#NW;#INT              1,994

In [117]:
#within illinois analysis

per_capita_exoneration = (351 * 100000) / 12670000


df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('State == "Illinois" and DNA == "DNA"')

percent = 63/351 * 100

#127 Ill + CIU and 500 total CIU

percent2 = 127/351 *100

#171 Ill + IO and 447 total IO

percent3 = 171/351 *100

print(df1)

print(percent)

print(percent2)

print(percent3)

print(per_capita_exoneration)

         Last Name   First Name   Age      Race     Sex     State     County  \
2        Abernathy  Christopher  17.0     White    Male  Illinois       Cook
13           Adams      Kenneth  21.0     Black    Male  Illinois       Cook
69        Andersen       Daniel  19.0     White    Male  Illinois       Cook
129         Bailey        Kevin  19.0     Black    Male  Illinois       Cook
163           Barr     Jonathan  14.0     Black    Male  Illinois       Cook
170      Batchelor        Corey  19.0     Black    Male  Illinois       Cook
249       Bradford   Marcellius  17.0     Black    Male  Illinois       Cook
283    Brooks, Jr.       Claude  35.0     Black    Male  Illinois       Cook
320        Bullock       Ronnie  27.0     Black    Male  Illinois       Cook
358           Cage        Dean   28.0     Black    Male  Illinois       Cook
388         Carini      William  28.0     White    Male  Illinois       Lake
496        Coleman       Nevest  25.0     Black    Male  Illinois       Cook
569           Cruz      Rolando  19.0  Hispanic    Male  Illinois     DuPage
605          Davis        Andre  19.0     Black    Male  Illinois  Champaign
685     DYesinguez    Alejandro  16.0  Hispanic    Male  Illinois       Lake
692         Dotson         Gary  20.0     White    Male  Illinois       Cook
732        Edwards        James  44.0     Black    Male  Illinois       Lake
766          Evans      Michael  17.0     Black    Male  Illinois       Cook
845         Fulton       Darryl  26.0     Black    Male  Illinois       Cook
846         Fulton         John  18.0     Black    Male  Illinois       Cook
893   Geralds, Jr.       Hubert  30.0     Black    Male  Illinois       Cook
903        Gillard        Larry  22.0     Black    Male  Illinois       Cook
934       Gonzalez        Angel  20.0  Hispanic    Male  Illinois       Lake
964           Gray    David A.   25.0     Black    Male  Illinois    Madison
965           Gray        Paula  17.0     Black  Female  Illinois       Cook
1038        Harden        James  16.0     Black    Male  Illinois       Cook
1099     Hernandez    Alejandro  19.0  Hispanic    Male  Illinois     DuPage
1123          Hill       Harold  16.0     Black    Male  Illinois       Cook
1143       Holland         Dana  25.0     Black    Male  Illinois       Cook
1144       Holland         Dana  25.0     Black    Male  Illinois       Cook
1251      Jimerson      Verneal  25.0     Black    Male  Illinois       Cook
1285       Johnson      Richard  31.0     Black    Male  Illinois       Cook
1322         Jones       Ronald  34.0     Black    Male  Illinois       Cook
1478      Linscott       Steven  26.0     White    Male  Illinois       Cook
1517         Lyons       Marcus  29.0     Black    Male  Illinois     DuPage
1581        Maxson         Mark  31.0     Black    Male  Illinois       Cook
1686        Miller        Jerry  23.0     Black    Male  Illinois       Cook
1706      Mitchell      Anthony  17.0     Black    Male  Illinois       Cook
1787          Nash   Alprentiss  20.0     Black    Male  Illinois       Cook
1844        Ollins       Calvin  14.0     Black    Male  Illinois       Cook
1845        Ollins        Larry  16.0     Black    Male  Illinois       Cook
1881        Palmer      Charles  43.0     Black    Male  Illinois      Macon
1906    Pattersonï¿½      Maurice  35.0     Black    Male  Illinois       Cook
1925     Pendleton       Marlon  35.0     Black    Male  Illinois       Cook
2027        Rainge       Willie  20.0     Black    Male  Illinois       Cook
2065      Reynolds       Donald  20.0     Black    Male  Illinois       Cook
2070    Richardson       Harold  16.0     Black    Male  Illinois       Cook
2085       Rivera          Juan  19.0  Hispanic    Male  Illinois       Lake
2135       Rollins      Lafonso  17.0     Black    Male  Illinois       Cook
2202      Saunders      Michael  15.0     Black    Male  Illinois       Cook
2203      Saunders        Yesar  18.0     Black    Male  Illinois       Cook
2204        Savory      Johnnie  14.0     Black    Male  Illinois     Peoria
2242         Sharp      Shainne  16.0     Black    Male  Illinois       Cook
2353        Starks       Bennie  26.0     Black    Male  Illinois       Lake
2406         Swift      Terrill  17.0     Black    Male  Illinois       Cook
2429        Taylor       Robert  14.0     Black    Male  Illinois       Cook
2437         Terry         Paul  17.0     Black    Male  Illinois       Cook
2440        Thames      Vincent  17.0     Black    Male  Illinois       Cook
2554          Veal       Robert  14.0     Black    Male  Illinois       Cook
2605       Wardell        Billy  21.0     Black    Male  Illinois       Cook
2704      Williams       Dennis  21.0     Black    Male  Illinois       Cook
2734        Willis         John  42.0     Black    Male  Illinois       Cook
2799    Young, Jr.          Dan  30.0     Black    Male  Illinois       Cook

                 Tags WorstCrimeDisplay  \
2      CIU;#CV;#H;#IO            Murder
13     CDC;#H;#IO;#JI            Murder
69              H;#IO            Murder
129        CDC;#H;#IO            Murder
163    CDC;#CV;#H;#IO            Murder
170        CDC;#H;#IO            Murder
249            CDC;#P        Kidnapping
283                CV   Child Sex Abuse
320                CV   Child Sex Abuse
358            CV;#IO   Child Sex Abuse
388               CIU    Sexual Assault
496   CDC;#CIU;#H;#IO            Murder
569    CDC;#CV;#H;#JI            Murder
605         CV;#H;#IO            Murder
685               NaN    Sexual Assault
692            CV;#NC    Sexual Assault
732                 H            Murder
766         CV;#H;#IO            Murder
845       CDC;#CIU;#H            Murder
846            CDC;#H            Murder
893                 H            Murder
903                IO    Sexual Assault
934           CIU;#IO    Sexual Assault
964                JI  Attempted Murder
965          F;#H;#JI            Murder
1038       CDC;#CV;#H            Murder
1099   CDC;#CV;#H;#JI            Murder
1123        A;#CDC;#H            Murder
1143               IO    Sexual Assault
1144               IO  Attempted Murder
1251   CDC;#H;#IO;#JI            Murder
1285              NaN    Sexual Assault
1322                H            Murder
1478                H            Murder
1517              NaN    Sexual Assault
1581       CIU;#CV;#H            Murder
1686               IO    Sexual Assault
1706           CDC;#H            Murder
1787      CDC;#CIU;#H            Murder
1844           CDC;#H            Murder
1845           CDC;#H            Murder
1881            H;#IO            Murder
1906            H;#IO            Murder
1925               IO    Sexual Assault
2027   CDC;#H;#IO;#JI            Murder
2065              NaN    Sexual Assault
2070           CDC;#H            Murder
2085    CV;#H;#IO;#JI            Murder
2135              NaN    Sexual Assault
2202           CDC;#H            Murder
2203           CDC;#H            Murder
2204        CV;#H;#IO            Murder
2242    CDC;#CV;#H;#P            Murder
2353               IO    Sexual Assault
2406           CDC;#H            Murder
2429       CDC;#CV;#H            Murder
2437        CV;#H;#IO            Murder
2440        CDC;#H;#P            Murder
2554    CDC;#CV;#H;#P            Murder
2605              NaN    Sexual Assault
2704   CDC;#H;#IO;#JI            Murder
2734              NaN    Sexual Assault
2799        A;#CDC;#H            Murder

                               List Add'l Crimes Recode  ...    *   FC  \
2                                         Rape;#Robbery  ...  NaN   FC
13                                     Rape;#Kidnapping  ...  NaN  NaN
69                                     Attempt, Violent  ...    *   FC
129                    Robbery;#Burglary/Unlawful Entry  ...    *   FC
163                                                Rape  ...  NaN  NaN
170                    Robbery;#Burglary/Unlawful Entry  ...    *   FC
249                                                 NaN  ...  NaN   FC
283                                                 NaN  ...    *  NaN
320                                          Kidnapping  ...  NaN  NaN
358                                                 NaN  ...  NaN  NaN
388                                                 NaN  ...    *  NaN
496                                    Rape;#Kidnapping  ...  NaN   FC
569           Rape;#Kidnapping;#Burglary/Unlawful Entry  ...  NaN   FC
605                         Child Sex Abuse;#Kidnapping  ...    *  NaN
685                             Burglary/Unlawful Entry  ...  NaN  NaN
692                                          Kidnapping  ...  NaN  NaN
732                                             Robbery  ...  NaN   FC
766                                    Rape;#Kidnapping  ...  NaN   FC
845                                                Rape  ...  NaN   FC
846                 Kidnapping;#Other Nonviolent Felony  ...    *   FC
893                                                Rape  ...    *   FC
903                                             Robbery  ...  NaN  NaN
934                                          Kidnapping  ...  NaN   FC
964                                       Rape;#Robbery  ...  NaN  NaN
965                                       Rape;#Perjury  ...  NaN   FC
1038                                               Rape  ...  NaN  NaN
1099          Rape;#Kidnapping;#Burglary/Unlawful Entry  ...  NaN   FC
1123                  Sexual Assault;#Arson;#Kidnapping  ...    *   FC
1143                                                NaN  ...  NaN  NaN
1144                                            Robbery  ...    *  NaN
1251                                               Rape  ...  NaN  NaN
1285       Robbery;#Kidnapping;#Burglary/Unlawful Entry  ...  NaN  NaN
1322                                               Rape  ...  NaN   FC
1478                                                NaN  ...  NaN   FC
1517                               Other Violent Felony  ...  NaN  NaN
1581                                               Rape  ...  NaN   FC
1686                                Robbery;#Kidnapping  ...  NaN  NaN
1706                Kidnapping;#Other Nonviolent Felony  ...    *   FC
1787  Robbery;#Attempt, Violent;#Burglary/Unlawful E...  ...    *  NaN
1844                                   Rape;#Kidnapping  ...  NaN   FC
1845                          Rape;#Robbery;#Kidnapping  ...  NaN  NaN
1881                                                NaN  ...    *  NaN
1906                                                NaN  ...  NaN  NaN
1925                                            Robbery  ...  NaN  NaN
2027                                               Rape  ...  NaN  NaN
2065                                            Robbery  ...  NaN  NaN
2070                                               Rape  ...  NaN   FC
2085                                                NaN  ...  NaN   FC
2135                                            Robbery  ...  NaN   FC
2202                                               Rape  ...  NaN   FC
2203                          Rape;#Robbery;#Kidnapping  ...  NaN  NaN
2204                                                NaN  ...    *   FC
2242                                               Rape  ...  NaN   FC
2353                          Assault;#Attempt, Violent  ...  NaN  NaN
2406                                               Rape  ...  NaN   FC
2429                                               Rape  ...  NaN   FC
2437                                   Rape;#Kidnapping  ...  NaN  NaN
2440                                               Rape  ...  NaN   FC
2554                                               Rape  ...  NaN   FC
2605                                            Robbery  ...  NaN  NaN
2704                         Sexual Assault;#Kidnapping  ...  NaN  NaN
2734                                            Robbery  ...  NaN  NaN
2799                  Sexual Assault;#Arson;#Kidnapping  ...    *   FC

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
2                 NaN           NaN     Yes                Yes  NaN
13                Yes           Yes     Yes                Yes  NaN
69                NaN           NaN     Yes                Yes  NaN
129               NaN           NaN     Yes                Yes  NaN
163               NaN           NaN     Yes                Yes  NaN
170               NaN           NaN     Yes                Yes  NaN
249               NaN           Yes     Yes                Yes  NaN
283               NaN           NaN     Yes                NaN  NaN
320               Yes           NaN     NaN                NaN  NaN
358               Yes           NaN     NaN                NaN  NaN
388               Yes           NaN     NaN                NaN  NaN
496               NaN           NaN     Yes                Yes  NaN
569               NaN           Yes     Yes                Yes  NaN
605               NaN           Yes     Yes                NaN  NaN
685               Yes           Yes     NaN                Yes  NaN
692               NaN           Yes     Yes                Yes  NaN
732               NaN           NaN     Yes                Yes  NaN
766               Yes           NaN     NaN                Yes  NaN
845               NaN           NaN     Yes                Yes  NaN
846               NaN           NaN     Yes                Yes  ILD
893               NaN           NaN     NaN                NaN  NaN
903               Yes           Yes     NaN                Yes  NaN
934               Yes           NaN     NaN                Yes  NaN
964               Yes           Yes     Yes                Yes  NaN
965               Yes           Yes     Yes                Yes  NaN
1038              NaN           NaN     Yes                Yes  NaN
1099              NaN           Yes     Yes                Yes  NaN
1123              NaN           Yes     Yes                Yes  NaN
1143              Yes           Yes     Yes                Yes  NaN
1144              NaN           NaN     Yes                NaN  NaN
1251              Yes           Yes     Yes                Yes  NaN
1285              Yes           NaN     NaN                NaN  ILD
1322              Yes           Yes     NaN                Yes  NaN
1478              NaN           Yes     NaN                Yes  NaN
1517              Yes           NaN     NaN                Yes  NaN
1581              NaN           NaN     Yes                Yes  NaN
1686              Yes           NaN     NaN                Yes  NaN
1706              NaN           NaN     Yes                Yes  ILD
1787              Yes           NaN     Yes                NaN  NaN
1844              NaN           Yes     Yes                Yes  NaN
1845              NaN           Yes     Yes                Yes  NaN
1881              NaN           Yes     Yes                NaN  NaN
1906              Yes           Yes     Yes                Yes  NaN
1925              Yes           Yes     Yes                Yes  NaN
2027              Yes           Yes     Yes                Yes  ILD
2065              Yes           Yes     Yes                Yes  NaN
2070              NaN           NaN     Yes                Yes  NaN
2085              Yes           Yes     Yes                Yes  NaN
2135              Yes           Yes     NaN                Yes  ILD
2202              NaN           NaN     Yes                Yes  NaN
2203              NaN           Yes     Yes                Yes  NaN
2204              NaN           NaN     Yes                Yes  ILD
2242              NaN           NaN     Yes                Yes  NaN
2353              NaN           Yes     Yes                Yes  NaN
2406              NaN           NaN     Yes                NaN  NaN
2429              NaN           NaN     Yes                Yes  NaN
2437              Yes           NaN     NaN                Yes  NaN
2440              NaN           NaN     Yes                Yes  NaN
2554              NaN           NaN     Yes                Yes  NaN
2605              Yes           Yes     Yes                Yes  NaN
2704              Yes           Yes     Yes                Yes  ILD
2734              Yes           Yes     Yes                Yes  NaN
2799              NaN           Yes     Yes                Yes  NaN

     Posting Date                             Yes Tags Date of Crime Year
2         2/13/15                      OF;#WH;#NW;#INT              1,984
13        8/29/11               PR;#OF;#WH;#NW;#KP;#WT              1,978
69        8/15/15                  OF;#WH;#NW;#INT;#PJ              1,980
129        2/3/18                  OF;#WH;#NW;#INT;#PJ              1,989
163       1/23/12                       OF;#WH;#NW;#WT              1,991
170        2/3/18                      OF;#WH;#NW;#INT              1,989
249       8/29/11                      OF;#FA;#NW;#INT              1,986
283       6/20/17                                  NaN              1,997
320       8/29/11                                  NaN              1,983
358       8/29/11                                  NaN              1,994
388       1/10/17                                  NaN              1,991
496       12/4/17                  OF;#WH;#NW;#PJ;#INT              1,994
569       8/29/11               PR;#OF;#FA;#WH;#NW;#PJ              1,983
605        7/6/12                                  NaN              1,980
685       8/29/11                               OF;#WH              1,989
692       8/29/11                       FA;#WH;#NW;#PJ              1,977
732       6/10/12                  OF;#WH;#NW;#PJ;#INT              1,994
766       8/29/11                       PR;#OF;#WH;#NW              1,976
845       12/4/17                  OF;#WH;#NW;#PJ;#INT              1,994
846       6/17/20  PR;#OF;#WH;#NW;#KP;#WT;#INT;#PJ;#PL              2,003
893       8/31/11                                  NaN              1,994
903       8/29/11                               FA;#WH              1,981
934       3/12/15                          OF;#NW;#INT              1,994
964       8/29/11                               PR;#NW              1,978
965       8/29/11          PR;#OF;#WH;#NW;#KP;#WT;#INT              1,978
1038      1/23/12                       OF;#WH;#NW;#WT              1,991
1099      8/29/11          PR;#OF;#FA;#WH;#NW;#INT;#PJ              1,983
1123      8/29/11                      OF;#NW;#WT;#INT              1,990
1143      8/29/11                           FA;#WH;#NW              1,993
1144      8/29/11                                  NaN              1,993
1251      8/29/11               PR;#OF;#WH;#NW;#KP;#WT              1,978
1285      8/29/11                                  NaN              1,990
1322      8/29/11                      OF;#WH;#NW;#INT              1,985
1478      8/29/11                           PR;#NW;#PL              1,980
1517      8/29/11               PR;#OF;#WH;#NW;#WT;#PL              1,987
1581      10/2/16                  OF;#WH;#NW;#INT;#PJ              1,992
1686      8/29/11                           FA;#WH;#NW              1,981
1706      6/17/20  PR;#OF;#WH;#NW;#KP;#WT;#INT;#PJ;#PL              2,003
1787      8/30/12                                  NaN              1,995
1844      8/29/11               OF;#FA;#WH;#NW;#WT;#PJ              1,986
1845      8/29/11               OF;#FA;#WH;#NW;#WT;#PJ              1,986
1881      12/4/16                                  NaN              1,998
1906      8/29/11           PR;#OF;#WH;#NW;#KP;#PJ;#PL              2,002
1925      8/29/11                   OF;#FA;#WH;#NW;#WT              1,992
2027      8/29/11               PR;#OF;#WH;#NW;#KP;#WT              1,978
2065      8/29/11                       FA;#WH;#NW;#PJ              1,986
2070      1/27/12                      OF;#WH;#NW;#INT              1,994

In [114]:
#new york analysis

per_capita_exoneration = (290 * 100000) / 8419000

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('State == "New York" and DNA == "DNA"')

percent = 50/540 * 100

#58 New York + CIU and 500 total CIU

percent2 = 57/499 *100

#52 New York + IO and 447 total IO

percent3 = 51/446 *100

print(df1)

print(percent)

print(percent2)

print(percent3)

print(per_capita_exoneration)

       Last Name    First Name   Age             Race     Sex     State  \
1          Abdal  Warith Habib  43.0            Black    Male  New York
126         Babb        Austin  20.0            Black    Male  New York
161       Barnes        Steven  19.0            White    Male  New York
303        Brown           Roy  29.0            White    Male  New York
347         Bush         Keith  17.0            Black    Male  New York
362      Callace       Leonard  30.0            White    Male  New York
381      Capozzi       Anthony  27.0            White    Male  New York
430     Chalmers         Terry  20.0            Black    Male  New York
511       Connor      Reginald  23.0            Black    Male  New York
534       Counts       Gregory  19.0            Black    Male  New York
588        Dabbs       Charles  27.0            Black    Male  New York
628         Days        Selwyn  32.0            Black    Male  New York
640        DeJac          Lynn  30.0            White  Female  New York
650     Deskovic       Jeffrey  16.0            White    Male  New York
776     Fappiano         Scott  21.0            White    Male  New York
796     Figueroa         Fancy  16.0         Hispanic  Female  New York
938     Gonzalez        Hector  18.0         Hispanic    Male  New York
978       Greene            Cy  19.0            Black    Male  New York
1022    Halstead        Dennis  26.0            White    Male  New York
1117       Hicks        Tyrone  41.0            Black    Male  New York
1299       Jones      Clifford  26.0            Black    Male  New York
1355    Kendrick       Jaythan  36.0            Black    Male  New York
1385       Kogut          John  19.0            White    Male  New York
1389      Kotler         Kerry  22.0            White    Male  New York
1401      Lackey           Dan  28.0            White    Male  New York
1596   McCaffrey       William  28.0            White    Male  New York
1597    McCallum         David  16.0            Black    Male  New York
1615      McCray        Antron  14.0            Black    Male  New York
1670      Mercer       Michael  40.0            Black    Male  New York
1805      Newton          Alan  21.0            Black    Male  New York
1835   O'Donnell         James  32.0            White    Male  New York
1856       Ortiz         Josue  22.0         Hispanic    Male  New York
1861       Ortiz        Victor  24.0         Hispanic    Male  New York
1874      Pacyon       Douglas  28.0            White    Male  New York
1916     Peacock       Freddie  26.0            Black    Male  New York
1939       Perry       VanDyke  21.0            Black    Male  New York
2061     Restivo          John  25.0            White    Male  New York
2074  Richardson         Kevin  14.0            Black    Male  New York
2155        Ruiz        Rafael  24.0         Hispanic    Male  New York
2167      Salaam         Yusef  14.0            Black    Male  New York
2193     Santana       Raymond  14.0         Hispanic    Male  New York
2357    Sterling         Frank  25.0            White    Male  New York
2386     Stuckey        Willie  16.0            Black    Male  New York
2578   Wagstaffe       Everton  23.0            Black    Male  New York
2608      Warney       Douglas  34.0            White    Male  New York
2631       Watts         Oneal  20.0            Black    Male  New York
2673       White       Michael  35.0  Native American    Male  New York
2751      Wilson       Sharrif  15.0            Black    Male  New York
2761        Wise         Korey  16.0            Black    Male  New York
2794    Yarbough       Anthony  18.0            Black    Male  New York

           County                Tags      WorstCrimeDisplay  \
1            Erie                  IO         Sexual Assault
126         Bronx          CIU;#CV;#H                 Murder
161        Oneida       CV;#H;#IO;#JI                 Murder
303        Cayuga           H;#IO;#JI                 Murder
347       Suffolk      CIU;#CV;#H;#IO                 Murder
362       Suffolk                 NaN         Sexual Assault
381          Erie                 NaN         Sexual Assault
430   Westchester                  IO         Sexual Assault
511         Kings                  CV             Kidnapping
534      New York         CIU;#IO;#NC         Sexual Assault
588   Westchester                  IO         Sexual Assault
628   Westchester               H;#IO                 Murder
640          Erie    CV;#F;#H;#JI;#NC                 Murder
650   Westchester           CV;#H;#IO                 Murder
776         Kings                  IO         Sexual Assault
796        Queens         F;#M;#NC;#P  Filing a False Report
938         Kings               H;#IO                 Murder
978         Kings                   H                 Murder
1022       Nassau  CDC;#CV;#H;#IO;#JI                 Murder
1117        Bronx                  IO         Sexual Assault
1299     New York              CIU;#H                 Murder
1355       Queens          CIU;#H;#IO                 Murder
1385       Nassau       CV;#H;#IO;#JI                 Murder
1389      Suffolk                 NaN         Sexual Assault
1401      Madison                  NC         Sexual Assault
1596     New York              IO;#NC         Sexual Assault
1597        Kings         CDC;#CIU;#H                 Murder
1615     New York             CDC;#IO         Sexual Assault
1670     New York                  CV         Sexual Assault
1805        Bronx                 NaN         Sexual Assault
1835     Richmond                 NaN         Sexual Assault
1856         Erie                H;#P           Manslaughter
1861       Orange              CV;#IO         Sexual Assault
1874         Erie                 NaN         Sexual Assault
1916       Monroe                  IO         Sexual Assault
1939     New York         CIU;#IO;#NC         Sexual Assault
2061       Nassau  CDC;#CV;#H;#IO;#JI                 Murder
2074     New York             CDC;#IO         Sexual Assault
2155     New York             CIU;#IO         Sexual Assault
2167     New York             CDC;#IO         Sexual Assault
2193     New York             CDC;#IO         Sexual Assault
2357       Monroe               H;#IO                 Murder
2386        Kings     CDC;#CIU;#H;#PH                 Murder
2578        Kings                  CV             Kidnapping
2608       Monroe               H;#IO                 Murder
2631        Bronx         CDC;#CIU;#P       Attempt, Violent
2673         Erie                  NC         Sexual Assault
2751        Kings     CDC;#CIU;#CV;#H                 Murder
2761     New York             CDC;#IO         Sexual Assault
2794        Kings     CDC;#CIU;#CV;#H                 Murder

                          List Add'l Crimes Recode  ...    *   FC  \
1                                          Robbery  ...  NaN  NaN
126                Assault;#Gun Possession or Sale  ...    *  NaN
161                           Rape;#Sexual Assault  ...  NaN  NaN
303                                            NaN  ...  NaN  NaN
347                               Attempt, Violent  ...    *   FC
362                           Other Violent Felony  ...  NaN  NaN
381                                            NaN  ...  NaN  NaN
430                                 Robbery;#Theft  ...  NaN  NaN
511                                            NaN  ...    *  NaN
534               Kidnapping;#Other Violent Felony  ...    *  NaN
588                                            NaN  ...  NaN  NaN
628                                            NaN  ...    *   FC
640                                            NaN  ...    *  NaN
650                                           Rape  ...  NaN   FC
776                        Burglary/Unlawful Entry  ...  NaN  NaN
796                                            NaN  ...    *   FC
938                        Illegal Use of a Weapon  ...  NaN  NaN
978                                        Robbery  ...    *  NaN
1022                                          Rape  ...  NaN  NaN
1117                                           NaN  ...    *  NaN
1299                        Rape;#Attempt, Violent  ...  NaN  NaN
1355                                       Robbery  ...    *  NaN
1385                                          Rape  ...  NaN   FC
1389              Robbery;#Burglary/Unlawful Entry  ...  NaN  NaN
1401                                           NaN  ...    *   FC
1596     Assault;#Kidnapping;#Other Violent Felony  ...    *  NaN
1597  Robbery;#Kidnapping;#Illegal Use of a Weapon  ...    *   FC
1615                              Robbery;#Assault  ...  NaN   FC
1670                                       Robbery  ...  NaN  NaN
1805                              Robbery;#Assault  ...  NaN  NaN
1835                                       Assault  ...  NaN  NaN
1856                                           NaN  ...    *   FC
1861                                           NaN  ...  NaN  NaN
1874                        Gun Possession or Sale  ...  NaN  NaN
1916                                           NaN  ...  NaN   FC
1939              Kidnapping;#Other Violent Felony  ...    *  NaN
2061                                          Rape  ...  NaN  NaN
2074                              Robbery;#Assault  ...  NaN   FC
2155                                       Robbery  ...  NaN  NaN
2167                              Robbery;#Assault  ...  NaN   FC
2193                                       Robbery  ...  NaN   FC
2357                                           NaN  ...  NaN   FC
2386  Robbery;#Kidnapping;#Illegal Use of a Weapon  ...    *   FC
2578                                           NaN  ...    *  NaN
2608                                           NaN  ...  NaN   FC
2631                                           NaN  ...    *  NaN
2673                                           NaN  ...    *  NaN
2751                                           NaN  ...  NaN   FC
2761                 Assault;#Other Violent Felony  ...  NaN   FC
2794                                           NaN  ...  NaN   FC

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
1                 Yes           Yes     NaN                Yes  NaN
126               Yes           NaN     Yes                Yes  NaN
161               Yes           Yes     Yes                NaN  NaN
303               NaN           Yes     Yes                Yes  NaN
347               NaN           Yes     Yes                Yes  ILD
362               Yes           NaN     NaN                NaN  NaN
381               Yes           NaN     NaN                NaN  NaN
430               Yes           NaN     NaN                NaN  NaN
511               NaN           NaN     Yes                Yes  ILD
534               NaN           NaN     Yes                NaN  NaN
588               Yes           Yes     NaN                NaN  NaN
628               NaN           NaN     Yes                NaN  ILD
640               NaN           NaN     Yes                NaN  NaN
650               NaN           NaN     NaN                Yes  NaN
776               Yes           NaN     NaN                NaN  NaN
796               NaN           NaN     NaN                NaN  NaN
938               Yes           NaN     NaN                NaN  NaN
978               Yes           NaN     Yes                Yes  ILD
1022              NaN           Yes     Yes                Yes  NaN
1117              Yes           NaN     NaN                NaN  NaN
1299              Yes           NaN     NaN                NaN  NaN
1355              NaN           NaN     Yes                Yes  NaN
1385              NaN           Yes     Yes                Yes  NaN
1389              Yes           NaN     Yes                Yes  NaN
1401              NaN           NaN     Yes                Yes  ILD
1596              NaN           NaN     Yes                NaN  NaN
1597              NaN           NaN     Yes                Yes  NaN
1615              NaN           Yes     Yes                Yes  NaN
1670              Yes           NaN     NaN                NaN  NaN
1805              Yes           NaN     NaN                NaN  NaN
1835              Yes           Yes     NaN                Yes  NaN
1856              NaN           NaN     NaN                Yes  NaN
1861              Yes           NaN     NaN                NaN  NaN
1874              Yes           NaN     NaN                NaN  NaN
1916              Yes           NaN     Yes                Yes  NaN
1939              NaN           NaN     Yes                NaN  NaN
2061              NaN           Yes     Yes                Yes  NaN
2074              NaN           Yes     Yes                Yes  NaN
2155              Yes           NaN     NaN                Yes  NaN
2167              NaN           Yes     Yes                Yes  NaN
2193              NaN           Yes     Yes                Yes  NaN
2357              NaN           NaN     NaN                NaN  NaN
2386              NaN           NaN     Yes                Yes  NaN
2578              NaN           NaN     Yes                Yes  ILD
2608              NaN           Yes     NaN                Yes  NaN
2631              Yes           NaN     Yes                NaN  NaN
2673              NaN           NaN     Yes                NaN  NaN
2751              NaN           Yes     Yes                Yes  ILD
2761              NaN           Yes     Yes                Yes  NaN
2794              NaN           Yes     Yes                Yes  ILD

     Posting Date                         Yes Tags Date of Crime Year
1         8/29/11                   OF;#WH;#NW;#WT              1,982
126       2/22/21                       OF;#NW;#PJ              2,010
161       8/29/11                              NaN              1,985
303       8/29/11                           PR;#WH              1,991
347        6/3/19  PR;#OF;#WH;#NW;#WT;#INT;#PJ;#PL              1,975
362       8/29/11                              NaN              1,985
381       8/29/11                              NaN              1,984
430       8/29/11                              NaN              1,986
511        8/2/15                           PR;#WH              1,992
534       5/10/18                              NaN              1,991
588       8/29/11                              NaN              1,982
628       9/25/17                              NaN              1,996
640       8/29/11                              NaN              1,993
650       8/29/11                  OF;#WH;#NW;#INT              1,989
776       8/29/11                              NaN              1,983
796       7/26/14                              NaN              1,997
938       8/29/11                              NaN              1,995
978       7/29/12                           OF;#WH              1,983
1022      8/29/11                       OF;#NW;#WT              1,984
1117      5/17/14                              NaN              1,998
1299     11/28/16                              NaN              1,980
1355      12/7/20           PR;#OF;#WH;#NW;#WT;#PJ              1,994
1385      8/29/11                      OF;#NW;#INT              1,984
1389      8/29/11               PR;#FA;#WH;#NW;#PJ              1,981
1401      8/29/11              PR;#OF;#WH;#NW;#INT              2,003
1596      8/29/11                              NaN              2,005
1597     10/16/14              OF;#WH;#NW;#WT;#INT              1,985
1615      8/29/11                       OF;#NW;#WT              1,989
1670      8/29/11                              NaN              1,991
1805      8/29/11                              NaN              1,984
1835      8/29/11                           PR;#WH              1,997
1856       2/4/15                           PR;#WH              2,004
1861      8/29/11                              NaN              1,983
1874      8/29/11                              NaN              1,984
1916      8/29/11                       OF;#NW;#PJ              1,976
1939      5/10/18                              NaN              1,991
2061      8/29/11                       OF;#NW;#WT              1,984
2074      8/29/11                       OF;#NW;#WT              1,989
2155      2/13/20                   OF;#WH;#NW;#WT              1,984
2167      8/29/11                       OF;#NW;#WT              1,989
2193      8/29/11                       OF;#NW;#WT              1,989
2357      8/29/11                              NaN              1,988
2386     10/16/14              OF;#WH;#NW;#WT;#INT              1,985
2578       8/2/15                           PR;#WH              1,992
2608      8/29/11                      OF;#NW;#INT              1,996
2631      2/16/21                              NaN              2,013
2673      5/20/15                              NaN              2,004
2751      2/11/14              OF;#NW;#WT;#INT;#PJ              1,992
2761      8/29/11                  OF;#WH;#NW;#INT              1,989
2794      2/11/14          OF;#WH;#NW;#WT;#INT;#PJ              1,992

[50 rows x 24 columns]
9.25925925925926
11.422845691382765
11.434977578475337
3.444589618719563

In [115]:
#within new york analysis

per_capita_exoneration = (290 * 100000) / 8419000

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('State == "New York" and DNA == "DNA"')

percent = 50/290 * 100

#58 New York + CIU and 500 total CIU

percent2 = 57/290 *100

#52 New York + IO and 447 total IO

percent3 = 51/290 *100

print(df1)

print(percent)

print(percent2)

print(percent3)

       Last Name    First Name   Age             Race     Sex     State  \
1          Abdal  Warith Habib  43.0            Black    Male  New York
126         Babb        Austin  20.0            Black    Male  New York
161       Barnes        Steven  19.0            White    Male  New York
303        Brown           Roy  29.0            White    Male  New York
347         Bush         Keith  17.0            Black    Male  New York
362      Callace       Leonard  30.0            White    Male  New York
381      Capozzi       Anthony  27.0            White    Male  New York
430     Chalmers         Terry  20.0            Black    Male  New York
511       Connor      Reginald  23.0            Black    Male  New York
534       Counts       Gregory  19.0            Black    Male  New York
588        Dabbs       Charles  27.0            Black    Male  New York
628         Days        Selwyn  32.0            Black    Male  New York
640        DeJac          Lynn  30.0            White  Female  New York
650     Deskovic       Jeffrey  16.0            White    Male  New York
776     Fappiano         Scott  21.0            White    Male  New York
796     Figueroa         Fancy  16.0         Hispanic  Female  New York
938     Gonzalez        Hector  18.0         Hispanic    Male  New York
978       Greene            Cy  19.0            Black    Male  New York
1022    Halstead        Dennis  26.0            White    Male  New York
1117       Hicks        Tyrone  41.0            Black    Male  New York
1299       Jones      Clifford  26.0            Black    Male  New York
1355    Kendrick       Jaythan  36.0            Black    Male  New York
1385       Kogut          John  19.0            White    Male  New York
1389      Kotler         Kerry  22.0            White    Male  New York
1401      Lackey           Dan  28.0            White    Male  New York
1596   McCaffrey       William  28.0            White    Male  New York
1597    McCallum         David  16.0            Black    Male  New York
1615      McCray        Antron  14.0            Black    Male  New York
1670      Mercer       Michael  40.0            Black    Male  New York
1805      Newton          Alan  21.0            Black    Male  New York
1835   O'Donnell         James  32.0            White    Male  New York
1856       Ortiz         Josue  22.0         Hispanic    Male  New York
1861       Ortiz        Victor  24.0         Hispanic    Male  New York
1874      Pacyon       Douglas  28.0            White    Male  New York
1916     Peacock       Freddie  26.0            Black    Male  New York
1939       Perry       VanDyke  21.0            Black    Male  New York
2061     Restivo          John  25.0            White    Male  New York
2074  Richardson         Kevin  14.0            Black    Male  New York
2155        Ruiz        Rafael  24.0         Hispanic    Male  New York
2167      Salaam         Yusef  14.0            Black    Male  New York
2193     Santana       Raymond  14.0         Hispanic    Male  New York
2357    Sterling         Frank  25.0            White    Male  New York
2386     Stuckey        Willie  16.0            Black    Male  New York
2578   Wagstaffe       Everton  23.0            Black    Male  New York
2608      Warney       Douglas  34.0            White    Male  New York
2631       Watts         Oneal  20.0            Black    Male  New York
2673       White       Michael  35.0  Native American    Male  New York
2751      Wilson       Sharrif  15.0            Black    Male  New York
2761        Wise         Korey  16.0            Black    Male  New York
2794    Yarbough       Anthony  18.0            Black    Male  New York

           County                Tags      WorstCrimeDisplay  \
1            Erie                  IO         Sexual Assault
126         Bronx          CIU;#CV;#H                 Murder
161        Oneida       CV;#H;#IO;#JI                 Murder
303        Cayuga           H;#IO;#JI                 Murder
347       Suffolk      CIU;#CV;#H;#IO                 Murder
362       Suffolk                 NaN         Sexual Assault
381          Erie                 NaN         Sexual Assault
430   Westchester                  IO         Sexual Assault
511         Kings                  CV             Kidnapping
534      New York         CIU;#IO;#NC         Sexual Assault
588   Westchester                  IO         Sexual Assault
628   Westchester               H;#IO                 Murder
640          Erie    CV;#F;#H;#JI;#NC                 Murder
650   Westchester           CV;#H;#IO                 Murder
776         Kings                  IO         Sexual Assault
796        Queens         F;#M;#NC;#P  Filing a False Report
938         Kings               H;#IO                 Murder
978         Kings                   H                 Murder
1022       Nassau  CDC;#CV;#H;#IO;#JI                 Murder
1117        Bronx                  IO         Sexual Assault
1299     New York              CIU;#H                 Murder
1355       Queens          CIU;#H;#IO                 Murder
1385       Nassau       CV;#H;#IO;#JI                 Murder
1389      Suffolk                 NaN         Sexual Assault
1401      Madison                  NC         Sexual Assault
1596     New York              IO;#NC         Sexual Assault
1597        Kings         CDC;#CIU;#H                 Murder
1615     New York             CDC;#IO         Sexual Assault
1670     New York                  CV         Sexual Assault
1805        Bronx                 NaN         Sexual Assault
1835     Richmond                 NaN         Sexual Assault
1856         Erie                H;#P           Manslaughter
1861       Orange              CV;#IO         Sexual Assault
1874         Erie                 NaN         Sexual Assault
1916       Monroe                  IO         Sexual Assault
1939     New York         CIU;#IO;#NC         Sexual Assault
2061       Nassau  CDC;#CV;#H;#IO;#JI                 Murder
2074     New York             CDC;#IO         Sexual Assault
2155     New York             CIU;#IO         Sexual Assault
2167     New York             CDC;#IO         Sexual Assault
2193     New York             CDC;#IO         Sexual Assault
2357       Monroe               H;#IO                 Murder
2386        Kings     CDC;#CIU;#H;#PH                 Murder
2578        Kings                  CV             Kidnapping
2608       Monroe               H;#IO                 Murder
2631        Bronx         CDC;#CIU;#P       Attempt, Violent
2673         Erie                  NC         Sexual Assault
2751        Kings     CDC;#CIU;#CV;#H                 Murder
2761     New York             CDC;#IO         Sexual Assault
2794        Kings     CDC;#CIU;#CV;#H                 Murder

                          List Add'l Crimes Recode  ...    *   FC  \
1                                          Robbery  ...  NaN  NaN
126                Assault;#Gun Possession or Sale  ...    *  NaN
161                           Rape;#Sexual Assault  ...  NaN  NaN
303                                            NaN  ...  NaN  NaN
347                               Attempt, Violent  ...    *   FC
362                           Other Violent Felony  ...  NaN  NaN
381                                            NaN  ...  NaN  NaN
430                                 Robbery;#Theft  ...  NaN  NaN
511                                            NaN  ...    *  NaN
534               Kidnapping;#Other Violent Felony  ...    *  NaN
588                                            NaN  ...  NaN  NaN
628                                            NaN  ...    *   FC
640                                            NaN  ...    *  NaN
650                                           Rape  ...  NaN   FC
776                        Burglary/Unlawful Entry  ...  NaN  NaN
796                                            NaN  ...    *   FC
938                        Illegal Use of a Weapon  ...  NaN  NaN
978                                        Robbery  ...    *  NaN
1022                                          Rape  ...  NaN  NaN
1117                                           NaN  ...    *  NaN
1299                        Rape;#Attempt, Violent  ...  NaN  NaN
1355                                       Robbery  ...    *  NaN
1385                                          Rape  ...  NaN   FC
1389              Robbery;#Burglary/Unlawful Entry  ...  NaN  NaN
1401                                           NaN  ...    *   FC
1596     Assault;#Kidnapping;#Other Violent Felony  ...    *  NaN
1597  Robbery;#Kidnapping;#Illegal Use of a Weapon  ...    *   FC
1615                              Robbery;#Assault  ...  NaN   FC
1670                                       Robbery  ...  NaN  NaN
1805                              Robbery;#Assault  ...  NaN  NaN
1835                                       Assault  ...  NaN  NaN
1856                                           NaN  ...    *   FC
1861                                           NaN  ...  NaN  NaN
1874                        Gun Possession or Sale  ...  NaN  NaN
1916                                           NaN  ...  NaN   FC
1939              Kidnapping;#Other Violent Felony  ...    *  NaN
2061                                          Rape  ...  NaN  NaN
2074                              Robbery;#Assault  ...  NaN   FC
2155                                       Robbery  ...  NaN  NaN
2167                              Robbery;#Assault  ...  NaN   FC
2193                                       Robbery  ...  NaN   FC
2357                                           NaN  ...  NaN   FC
2386  Robbery;#Kidnapping;#Illegal Use of a Weapon  ...    *   FC
2578                                           NaN  ...    *  NaN
2608                                           NaN  ...  NaN   FC
2631                                           NaN  ...    *  NaN
2673                                           NaN  ...    *  NaN
2751                                           NaN  ...  NaN   FC
2761                 Assault;#Other Violent Felony  ...  NaN   FC
2794                                           NaN  ...  NaN   FC

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
1                 Yes           Yes     NaN                Yes  NaN
126               Yes           NaN     Yes                Yes  NaN
161               Yes           Yes     Yes                NaN  NaN
303               NaN           Yes     Yes                Yes  NaN
347               NaN           Yes     Yes                Yes  ILD
362               Yes           NaN     NaN                NaN  NaN
381               Yes           NaN     NaN                NaN  NaN
430               Yes           NaN     NaN                NaN  NaN
511               NaN           NaN     Yes                Yes  ILD
534               NaN           NaN     Yes                NaN  NaN
588               Yes           Yes     NaN                NaN  NaN
628               NaN           NaN     Yes                NaN  ILD
640               NaN           NaN     Yes                NaN  NaN
650               NaN           NaN     NaN                Yes  NaN
776               Yes           NaN     NaN                NaN  NaN
796               NaN           NaN     NaN                NaN  NaN
938               Yes           NaN     NaN                NaN  NaN
978               Yes           NaN     Yes                Yes  ILD
1022              NaN           Yes     Yes                Yes  NaN
1117              Yes           NaN     NaN                NaN  NaN
1299              Yes           NaN     NaN                NaN  NaN
1355              NaN           NaN     Yes                Yes  NaN
1385              NaN           Yes     Yes                Yes  NaN
1389              Yes           NaN     Yes                Yes  NaN
1401              NaN           NaN     Yes                Yes  ILD
1596              NaN           NaN     Yes                NaN  NaN
1597              NaN           NaN     Yes                Yes  NaN
1615              NaN           Yes     Yes                Yes  NaN
1670              Yes           NaN     NaN                NaN  NaN
1805              Yes           NaN     NaN                NaN  NaN
1835              Yes           Yes     NaN                Yes  NaN
1856              NaN           NaN     NaN                Yes  NaN
1861              Yes           NaN     NaN                NaN  NaN
1874              Yes           NaN     NaN                NaN  NaN
1916              Yes           NaN     Yes                Yes  NaN
1939              NaN           NaN     Yes                NaN  NaN
2061              NaN           Yes     Yes                Yes  NaN
2074              NaN           Yes     Yes                Yes  NaN
2155              Yes           NaN     NaN                Yes  NaN
2167              NaN           Yes     Yes                Yes  NaN
2193              NaN           Yes     Yes                Yes  NaN
2357              NaN           NaN     NaN                NaN  NaN
2386              NaN           NaN     Yes                Yes  NaN
2578              NaN           NaN     Yes                Yes  ILD
2608              NaN           Yes     NaN                Yes  NaN
2631              Yes           NaN     Yes                NaN  NaN
2673              NaN           NaN     Yes                NaN  NaN
2751              NaN           Yes     Yes                Yes  ILD
2761              NaN           Yes     Yes                Yes  NaN
2794              NaN           Yes     Yes                Yes  ILD

     Posting Date                         Yes Tags Date of Crime Year
1         8/29/11                   OF;#WH;#NW;#WT              1,982
126       2/22/21                       OF;#NW;#PJ              2,010
161       8/29/11                              NaN              1,985
303       8/29/11                           PR;#WH              1,991
347        6/3/19  PR;#OF;#WH;#NW;#WT;#INT;#PJ;#PL              1,975
362       8/29/11                              NaN              1,985
381       8/29/11                              NaN              1,984
430       8/29/11                              NaN              1,986
511        8/2/15                           PR;#WH              1,992
534       5/10/18                              NaN              1,991
588       8/29/11                              NaN              1,982
628       9/25/17                              NaN              1,996
640       8/29/11                              NaN              1,993
650       8/29/11                  OF;#WH;#NW;#INT              1,989
776       8/29/11                              NaN              1,983
796       7/26/14                              NaN              1,997
938       8/29/11                              NaN              1,995
978       7/29/12                           OF;#WH              1,983
1022      8/29/11                       OF;#NW;#WT              1,984
1117      5/17/14                              NaN              1,998
1299     11/28/16                              NaN              1,980
1355      12/7/20           PR;#OF;#WH;#NW;#WT;#PJ              1,994
1385      8/29/11                      OF;#NW;#INT              1,984
1389      8/29/11               PR;#FA;#WH;#NW;#PJ              1,981
1401      8/29/11              PR;#OF;#WH;#NW;#INT              2,003
1596      8/29/11                              NaN              2,005
1597     10/16/14              OF;#WH;#NW;#WT;#INT              1,985
1615      8/29/11                       OF;#NW;#WT              1,989
1670      8/29/11                              NaN              1,991
1805      8/29/11                              NaN              1,984
1835      8/29/11                           PR;#WH              1,997
1856       2/4/15                           PR;#WH              2,004
1861      8/29/11                              NaN              1,983
1874      8/29/11                              NaN              1,984
1916      8/29/11                       OF;#NW;#PJ              1,976
1939      5/10/18                              NaN              1,991
2061      8/29/11                       OF;#NW;#WT              1,984
2074      8/29/11                       OF;#NW;#WT              1,989
2155      2/13/20                   OF;#WH;#NW;#WT              1,984
2167      8/29/11                       OF;#NW;#WT              1,989
2193      8/29/11                       OF;#NW;#WT              1,989
2357      8/29/11                              NaN              1,988
2386     10/16/14              OF;#WH;#NW;#WT;#INT              1,985
2578       8/2/15                           PR;#WH              1,992
2608      8/29/11                      OF;#NW;#INT              1,996
2631      2/16/21                              NaN              2,013
2673      5/20/15                              NaN              2,004
2751      2/11/14              OF;#NW;#WT;#INT;#PJ              1,992
2761      8/29/11                  OF;#WH;#NW;#INT              1,989
2794      2/11/14          OF;#WH;#NW;#WT;#INT;#PJ              1,992

[50 rows x 24 columns]
17.24137931034483
19.655172413793103
17.586206896551722

In [113]:
#louisiana analysis

per_capita_exoneration = (63 * 100000) / 4649000

df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('State == "Louisiana" and DNA == "DNA"')

percent = 19/63 * 100

#4 CIU and 63 total LA

percent2 = 4/63 *100

#31 IO and 63 total LA

percent3 = 31/63 *100

print(df1)

print(percent)

print(percent2)

print(percent3)

print(per_capita_exoneration)



print(per_capita_exoneration)

       Last Name       First Name   Age   Race   Sex      State       County  \
37     Alexander          Malcolm  19.0  Black  Male  Louisiana    Jefferson
207      Bibbins             Gene  29.0  Black  Male  Louisiana    LA Parish
292        Brown           Dennis  16.0  Black  Male  Louisiana  St. Tammany
300        Brown           Nathan  23.0  Black  Male  Louisiana    Jefferson
442      Charles            Clyde  26.0  Black  Male  Louisiana   Terrebonne
486         Coco            Allen  26.0  Black  Male  Louisiana    Calcasieu
814        Floyd             John  31.0  White  Male  Louisiana      Orleans
1082       Hayes           Travis  17.0  Black  Male  Louisiana    Jefferson
1121        Hill           Darrin  26.0  Black  Male  Louisiana      Orleans
1220     Jackson           Willie  17.0  Black  Male  Louisiana    Jefferson
1229       James            Henry  20.0  Black  Male  Louisiana    Jefferson
1255     Johnson          Anthony  27.0  Black  Male  Louisiana   Washington
1286     Johnson           Rickey  26.0  Black  Male  Louisiana       Sabine
1465       Lewis             Ryan  15.0  Black  Male  Louisiana      Orleans
1579    Matthews             Ryan  17.0  Black  Male  Louisiana    Jefferson
2317       Smith          Kaliegh  31.0  Black  Male  Louisiana      Orleans
2441  Thibodeaux            Damon  21.0  White  Male  Louisiana    Jefferson
2720    Williams  Michael Anthony  16.0  Black  Male  Louisiana      Jackson
2730      Willis           Calvin  21.0  Black  Male  Louisiana        Caddo

            Tags WorstCrimeDisplay  \
37            IO    Sexual Assault
207       CV;#IO   Child Sex Abuse
292           IO    Sexual Assault
300           IO    Sexual Assault
442          NaN    Sexual Assault
486           IO    Sexual Assault
814        H;#IO            Murder
1082       H;#IO            Murder
1121          IO    Sexual Assault
1220         NaN    Sexual Assault
1229         NaN    Sexual Assault
1255       H;#IO            Murder
1286          IO    Sexual Assault
1465          CV  Attempted Murder
1579      CDC;#H            Murder
2317  CIU;#H;#IO            Murder
2441   CV;#H;#IO            Murder
2720          IO    Sexual Assault
2730      CV;#IO   Child Sex Abuse

                           List Add'l Crimes Recode  ...    *   FC  \
37                                              NaN  ...    *  NaN
207                         Burglary/Unlawful Entry  ...  NaN  NaN
292   Other Violent Felony;#Burglary/Unlawful Entry  ...  NaN   FC
300                                             NaN  ...  NaN  NaN
442                                             NaN  ...  NaN  NaN
486                         Burglary/Unlawful Entry  ...  NaN  NaN
814                                             NaN  ...    *   FC
1082                                            NaN  ...  NaN   FC
1121                            Robbery;#Kidnapping  ...    *  NaN
1220                                        Robbery  ...  NaN  NaN
1229                                            NaN  ...  NaN  NaN
1255                                            NaN  ...  NaN   FC
1286                                            NaN  ...  NaN  NaN
1465                                            NaN  ...    *  NaN
1579                                            NaN  ...  NaN  NaN
2317                                            NaN  ...    *  NaN
2441                                           Rape  ...  NaN   FC
2720                                            NaN  ...  NaN  NaN
2730                                            NaN  ...  NaN  NaN

      MistakenWitness FalseEvidence Perjury OfficialMisconduct  ILD  \
37                Yes           NaN     Yes                Yes  ILD
207               Yes           Yes     Yes                Yes  NaN
292               Yes           Yes     NaN                Yes  NaN
300               Yes           NaN     NaN                NaN  ILD
442               Yes           Yes     NaN                NaN  NaN
486               Yes           NaN     NaN                NaN  NaN
814               NaN           NaN     Yes                Yes  NaN
1082              NaN           NaN     NaN                Yes  NaN
1121              Yes           NaN     NaN                NaN  NaN
1220              Yes           Yes     NaN                NaN  NaN
1229              Yes           NaN     NaN                NaN  ILD
1255              Yes           Yes     Yes                Yes  NaN
1286              Yes           NaN     NaN                NaN  NaN
1465              Yes           NaN     NaN                NaN  NaN
1579              Yes           NaN     Yes                Yes  NaN
2317              Yes           NaN     Yes                Yes  ILD
2441              Yes           NaN     NaN                Yes  NaN
2720              Yes           NaN     NaN                NaN  NaN
2730              Yes           NaN     NaN                Yes  NaN

     Posting Date                 Yes Tags Date of Crime Year
37         2/6/18           PR;#OF;#NW;#PJ              1,979
207       8/29/11       PR;#FA;#WH;#NW;#PJ              1,986
292       8/29/11          OF;#WH;#NW;#INT              1,984
300       6/25/14                      NaN              1,997
442       8/29/11                      NaN              1,981
486       8/29/11                      NaN              1,995
814       12/3/18  PR;#OF;#WH;#NW;#INT;#PJ              1,980
1082      8/29/11                   PR;#WH              1,997
1121       7/3/12                      NaN              1,992
1220      8/29/11                      NaN              1,986
1229      1/13/12                      NaN              1,981
1255      8/29/11       PR;#OF;#WH;#NW;#PJ              1,984
1286      8/29/11                      NaN              1,982
1465       4/6/20                      NaN              2,002
1579      8/29/11                   PR;#WH              1,997
2317      6/25/21   PR;#OF;#WH;#NW;#KP;#WT              2,007
2441      9/28/12      PR;#OF;#WH;#NW;#INT              1,996
2720      8/29/11                      NaN              1,981
2730      8/29/11               OF;#WH;#NW              1,981

[19 rows x 24 columns]
30.158730158730158
6.349206349206349
49.2063492063492
1.3551301355130136
1.3551301355130136

In [1]:
#fed analysis

fed_total = 21 + 13 + 12 + 6 + 17 + 5 + 15 + 8 + 6 + 7 + 2 + 9 

fed_percent = (fed_total / 2809) * 100

print(fed_total)

print(fed_percent)

#DNA for fed

dna_fed = 1/121 * 100

#NO USE OF CIU OR IO

PR_dna = 63/121 * 100

OM_dna = 77/121 * 100

per_dna = 73/121 * 100

false_ev_fed = 11/121 * 100

print(dna_fed)

print(PR_dna)

print(OM_dna)

print(per_dna)

print(false_ev_fed)

121
4.307582769668921
0.8264462809917356
52.066115702479344
63.63636363636363
60.33057851239669
9.090909090909092

In [124]:
#new hampshire analysis

per_capita = (2 * 100000) / 1360000

print(per_capita)

0.14705882352941177

In [125]:
#maryland analysis

per_capita = (40 * 100000) / 6046000

print(per_capita)

0.6615944426066821

In [ ]:
#wyoming analysis

In [3]:
#south carolina analysis

per_capita = (9 * 100000) / 5149000

print(per_capita)

0.1747912215964265

In [6]:
total_ciu = 500/1820 * 100

ciu_last_five_years = 272/689 * 100

print(total_ciu)

print(ciu_last_five_years)

27.472527472527474
39.477503628447025

In [18]:
df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('State == "Illinois" and Exonerated > 2002 and DNA == "DNA"')

exonerated_percent = 293/351 * 100

print(df1)


print(exonerated_percent)

        Last Name   First Name   Age      Race   Sex     State     County  \
2       Abernathy  Christopher  17.0     White  Male  Illinois       Cook
69       Andersen       Daniel  19.0     White  Male  Illinois       Cook
129        Bailey        Kevin  19.0     Black  Male  Illinois       Cook
163          Barr     Jonathan  14.0     Black  Male  Illinois       Cook
170     Batchelor        Corey  19.0     Black  Male  Illinois       Cook
283   Brooks, Jr.       Claude  35.0     Black  Male  Illinois       Cook
358          Cage        Dean   28.0     Black  Male  Illinois       Cook
388        Carini      William  28.0     White  Male  Illinois       Lake
496       Coleman       Nevest  25.0     Black  Male  Illinois       Cook
605         Davis        Andre  19.0     Black  Male  Illinois  Champaign
732       Edwards        James  44.0     Black  Male  Illinois       Lake
766         Evans      Michael  17.0     Black  Male  Illinois       Cook
845        Fulton       Darryl  26.0     Black  Male  Illinois       Cook
846        Fulton         John  18.0     Black  Male  Illinois       Cook
903       Gillard        Larry  22.0     Black  Male  Illinois       Cook
934      Gonzalez        Angel  20.0  Hispanic  Male  Illinois       Lake
1038       Harden        James  16.0     Black  Male  Illinois       Cook
1123         Hill       Harold  16.0     Black  Male  Illinois       Cook
1143      Holland         Dana  25.0     Black  Male  Illinois       Cook
1144      Holland         Dana  25.0     Black  Male  Illinois       Cook
1517        Lyons       Marcus  29.0     Black  Male  Illinois     DuPage
1581       Maxson         Mark  31.0     Black  Male  Illinois       Cook
1686       Miller        Jerry  23.0     Black  Male  Illinois       Cook
1706     Mitchell      Anthony  17.0     Black  Male  Illinois       Cook
1787         Nash   Alprentiss  20.0     Black  Male  Illinois       Cook
1881       Palmer      Charles  43.0     Black  Male  Illinois      Macon
1906   Pattersonï¿½      Maurice  35.0     Black  Male  Illinois       Cook
1925    Pendleton       Marlon  35.0     Black  Male  Illinois       Cook
2070   Richardson       Harold  16.0     Black  Male  Illinois       Cook
2085      Rivera          Juan  19.0  Hispanic  Male  Illinois       Lake
2135      Rollins      Lafonso  17.0     Black  Male  Illinois       Cook
2202     Saunders      Michael  15.0     Black  Male  Illinois       Cook
2204       Savory      Johnnie  14.0     Black  Male  Illinois     Peoria
2242        Sharp      Shainne  16.0     Black  Male  Illinois       Cook
2353       Starks       Bennie  26.0     Black  Male  Illinois       Lake
2406        Swift      Terrill  17.0     Black  Male  Illinois       Cook
2429       Taylor       Robert  14.0     Black  Male  Illinois       Cook
2437        Terry         Paul  17.0     Black  Male  Illinois       Cook
2440       Thames      Vincent  17.0     Black  Male  Illinois       Cook
2554         Veal       Robert  14.0     Black  Male  Illinois       Cook
2799   Young, Jr.          Dan  30.0     Black  Male  Illinois       Cook

                 Tags WorstCrimeDisplay  \
2      CIU;#CV;#H;#IO            Murder
69              H;#IO            Murder
129        CDC;#H;#IO            Murder
163    CDC;#CV;#H;#IO            Murder
170        CDC;#H;#IO            Murder
283                CV   Child Sex Abuse
358            CV;#IO   Child Sex Abuse
388               CIU    Sexual Assault
496   CDC;#CIU;#H;#IO            Murder
605         CV;#H;#IO            Murder
732                 H            Murder
766         CV;#H;#IO            Murder
845       CDC;#CIU;#H            Murder
846            CDC;#H            Murder
903                IO    Sexual Assault
934           CIU;#IO    Sexual Assault
1038       CDC;#CV;#H            Murder
1123        A;#CDC;#H            Murder
1143               IO    Sexual Assault
1144               IO  Attempted Murder
1517              NaN    Sexual Assault
1581       CIU;#CV;#H            Murder
1686               IO    Sexual Assault
1706           CDC;#H            Murder
1787      CDC;#CIU;#H            Murder
1881            H;#IO            Murder
1906            H;#IO            Murder
1925               IO    Sexual Assault
2070           CDC;#H            Murder
2085    CV;#H;#IO;#JI            Murder
2135              NaN    Sexual Assault
2202           CDC;#H            Murder
2204        CV;#H;#IO            Murder
2242    CDC;#CV;#H;#P            Murder
2353               IO    Sexual Assault
2406           CDC;#H            Murder
2429       CDC;#CV;#H            Murder
2437        CV;#H;#IO            Murder
2440        CDC;#H;#P            Murder
2554    CDC;#CV;#H;#P            Murder
2799        A;#CDC;#H            Murder

                               List Add'l Crimes Recode  ... MistakenWitness  \
2                                         Rape;#Robbery  ...             NaN
69                                     Attempt, Violent  ...             NaN
129                    Robbery;#Burglary/Unlawful Entry  ...             NaN
163                                                Rape  ...             NaN
170                    Robbery;#Burglary/Unlawful Entry  ...             NaN
283                                                 NaN  ...             NaN
358                                                 NaN  ...             Yes
388                                                 NaN  ...             Yes
496                                    Rape;#Kidnapping  ...             NaN
605                         Child Sex Abuse;#Kidnapping  ...             NaN
732                                             Robbery  ...             NaN
766                                    Rape;#Kidnapping  ...             Yes
845                                                Rape  ...             NaN
846                 Kidnapping;#Other Nonviolent Felony  ...             NaN
903                                             Robbery  ...             Yes
934                                          Kidnapping  ...             Yes
1038                                               Rape  ...             NaN
1123                  Sexual Assault;#Arson;#Kidnapping  ...             NaN
1143                                                NaN  ...             Yes
1144                                            Robbery  ...             NaN
1517                               Other Violent Felony  ...             Yes
1581                                               Rape  ...             NaN
1686                                Robbery;#Kidnapping  ...             Yes
1706                Kidnapping;#Other Nonviolent Felony  ...             NaN
1787  Robbery;#Attempt, Violent;#Burglary/Unlawful E...  ...             Yes
1881                                                NaN  ...             NaN
1906                                                NaN  ...             Yes
1925                                            Robbery  ...             Yes
2070                                               Rape  ...             NaN
2085                                                NaN  ...             Yes
2135                                            Robbery  ...             Yes
2202                                               Rape  ...             NaN
2204                                                NaN  ...             NaN
2242                                               Rape  ...             NaN
2353                          Assault;#Attempt, Violent  ...             NaN
2406                                               Rape  ...             NaN
2429                                               Rape  ...             NaN
2437                                   Rape;#Kidnapping  ...             Yes
2440                                               Rape  ...             NaN
2554                                               Rape  ...             NaN
2799                  Sexual Assault;#Arson;#Kidnapping  ...             NaN

      FalseEvidence  Perjury OfficialMisconduct  ILD Posting Date  \
2               NaN      Yes                Yes  NaN      2/13/15
69              NaN      Yes                Yes  NaN      8/15/15
129             NaN      Yes                Yes  NaN       2/3/18
163             NaN      Yes                Yes  NaN      1/23/12
170             NaN      Yes                Yes  NaN       2/3/18
283             NaN      Yes                NaN  NaN      6/20/17
358             NaN      NaN                NaN  NaN      8/29/11
388             NaN      NaN                NaN  NaN      1/10/17
496             NaN      Yes                Yes  NaN      12/4/17
605             Yes      Yes                NaN  NaN       7/6/12
732             NaN      Yes                Yes  NaN      6/10/12
766             NaN      NaN                Yes  NaN      8/29/11
845             NaN      Yes                Yes  NaN      12/4/17
846             NaN      Yes                Yes  ILD      6/17/20
903             Yes      NaN                Yes  NaN      8/29/11
934             NaN      NaN                Yes  NaN      3/12/15
1038            NaN      Yes                Yes  NaN      1/23/12
1123            Yes      Yes                Yes  NaN      8/29/11
1143            Yes      Yes                Yes  NaN      8/29/11
1144            NaN      Yes                NaN  NaN      8/29/11
1517            NaN      NaN                Yes  NaN      8/29/11
1581            NaN      Yes                Yes  NaN      10/2/16
1686            NaN      NaN                Yes  NaN      8/29/11
1706            NaN      Yes                Yes  ILD      6/17/20
1787            NaN      Yes                NaN  NaN      8/30/12
1881            Yes      Yes                NaN  NaN      12/4/16
1906            Yes      Yes                Yes  NaN      8/29/11
1925            Yes      Yes                Yes  NaN      8/29/11
2070            NaN      Yes                Yes  NaN      1/27/12
2085            Yes      Yes                Yes  NaN       2/7/12
2135            Yes      NaN                Yes  ILD      8/29/11
2202            NaN      Yes                Yes  NaN      1/27/12
2204            NaN      Yes                Yes  ILD       2/2/15
2242            NaN      Yes                Yes  NaN      1/23/12
2353            Yes      Yes                Yes  NaN       1/7/13
2406            NaN      Yes                NaN  NaN      1/27/12
2429            NaN      Yes                Yes  NaN      1/15/12
2437            NaN      NaN                Yes  NaN      8/29/11
2440            NaN      Yes                Yes  NaN      1/27/12
2554            NaN      Yes                Yes  NaN      1/15/12
2799            Yes      Yes                Yes  NaN      8/29/11

                                 Yes Tags Date of Crime Year Unnamed: 24  CIU
2                         OF;#WH;#NW;#INT              1,984         NaN  Yes
69                    OF;#WH;#NW;#INT;#PJ              1,980         NaN  NaN
129                   OF;#WH;#NW;#INT;#PJ              1,989         NaN  NaN
163                        OF;#WH;#NW;#WT              1,991         NaN  NaN
170                       OF;#WH;#NW;#INT              1,989         NaN  NaN
283                                   NaN              1,997         NaN  NaN
358                                   NaN              1,994         NaN  NaN
388                                   NaN              1,991         NaN  NaN
496                   OF;#WH;#NW;#PJ;#INT              1,994         NaN  NaN
605                                   NaN              1,980         NaN  NaN
732                   OF;#WH;#NW;#PJ;#INT              1,994         NaN  NaN
766                        PR;#OF;#WH;#NW              1,976         NaN  NaN
845                   OF;#WH;#NW;#PJ;#INT              1,994         NaN  NaN
846   PR;#OF;#WH;#NW;#KP;#WT;#INT;#PJ;#PL              2,003         NaN  NaN
903                                FA;#WH              1,981         NaN  NaN
934                           OF;#NW;#INT              1,994         NaN  NaN
1038                       OF;#WH;#NW;#WT              1,991         NaN  NaN
1123                      OF;#NW;#WT;#INT              1,990         NaN  NaN
1143                           FA;#WH;#NW              1,993         NaN  NaN
1144                                  NaN              1,993         NaN  NaN
1517               PR;#OF;#WH;#NW;#WT;#PL              1,987         NaN  NaN
1581                  OF;#WH;#NW;#INT;#PJ              1,992         NaN  NaN
1686                           FA;#WH;#NW              1,981         NaN  NaN
1706  PR;#OF;#WH;#NW;#KP;#WT;#INT;#PJ;#PL              2,003         NaN  NaN
1787                                  NaN              1,995         NaN  NaN
1881                                  NaN              1,998         NaN  NaN
1906           PR;#OF;#WH;#NW;#KP;#PJ;#PL              2,002         NaN  NaN
1925                   OF;#FA;#WH;#NW;#WT              1,992         NaN  NaN
2070                      OF;#WH;#NW;#INT              1,994         NaN  NaN
2085                          OF;#NW;#INT              1,992         NaN  NaN
2135                  OF;#FA;#WH;#NW;#INT              1,993         NaN  NaN
2202                      OF;#WH;#NW;#INT              1,994         NaN  NaN
2204                      OF;#WH;#NW;#INT              1,977         NaN  NaN
2242                       OF;#WH;#NW;#WT              1,991         NaN  NaN
2353                       FA;#WH;#NW;#PJ              1,986         NaN  NaN
2406                                  NaN              1,994         NaN  NaN
2429                      OF;#WH;#NW;#INT              1,991         NaN  NaN
2437                       PR;#OF;#WH;#NW              1,976         NaN  NaN
2440                          OF;#NW;#INT              1,994         NaN  NaN
2554                       OF;#WH;#NW;#WT              1,991         NaN  NaN
2799                  OF;#WH;#NW;#WT;#INT              1,990         NaN  NaN

[41 rows x 26 columns]
83.47578347578347

In [26]:
df = pd.read_csv('/Users/kanshruti/Downloads/Exoneration Data.csv')

df1 = df.query('State == "Louisiana" and Exonerated > 2000')

exonerated_percent = 293/351 * 100

print(df1)


print(exonerated_percent)

          Last Name       First Name   Age      Race     Sex      State  \
16            Adams         Reginald  26.0     Black    Male  Louisiana
37        Alexander          Malcolm  19.0     Black    Male  Louisiana
199         Beridon           Cheryl  23.0     Black  Female  Louisiana
207         Bibbins             Gene  29.0     Black    Male  Louisiana
267          Bright           Dan L.  35.0     Black    Male  Louisiana
268          Bright          Gregory  20.0     Black    Male  Louisiana
269          Briley           Yutico  19.0     Black    Male  Louisiana
292           Brown           Dennis  16.0     Black    Male  Louisiana
300           Brown           Nathan  23.0     Black    Male  Louisiana
337         Burrell           Albert  30.0     White    Male  Louisiana
474      Clark, Jr.            Royal  24.0     Black    Male  Louisiana
486            Coco            Allen  26.0     Black    Male  Louisiana
551        Crawford         Rodricus  22.0     Black    Male  Louisiana
579          Curley           Catina  32.0     Black  Female  Louisiana
616      Davis, Jr.            Glenn  18.0     Black    Male  Louisiana
626            Daye          Anthony  30.0     Black    Male  Louisiana
643         Delmore            Larry  22.0     Black    Male  Louisiana
668          Dilosa          Douglas  35.0     White    Male  Louisiana
814           Floyd             John  31.0     White    Male  Louisiana
820            Ford            Glenn  34.0     Black    Male  Louisiana
1082          Hayes           Travis  17.0     Black    Male  Louisiana
1121           Hill           Darrin  26.0     Black    Male  Louisiana
1176         Hudson         Jermaine  20.0     Black    Male  Louisiana
1220        Jackson           Willie  17.0     Black    Male  Louisiana
1229          James            Henry  20.0     Black    Male  Louisiana
1255        Johnson          Anthony  27.0     Black    Male  Louisiana
1286        Johnson           Rickey  26.0     Black    Male  Louisiana
1321          Jones           Robert  19.0     Black    Male  Louisiana
1327          Jones          Wilbert  18.0     Black    Male  Louisiana
1400         LaBran           Dwight  23.0     Black    Male  Louisiana
1429        Lazzell            David  32.0     White    Male  Louisiana
1465          Lewis             Ryan  15.0     Black    Male  Louisiana
1579       Matthews             Ryan  17.0     Black    Male  Louisiana
1674         Meyers         Terrence  21.0     Black    Male  Louisiana
1757         Morgan          JerYese  17.0     Black    Male  Louisiana
2033  Ramirez-Power           Hollie  36.0     White  Female  Louisiana
2148          Ruano            Julio  42.0  Hispanic    Male  Louisiana
2241        Shannon          Michael  41.0     Black    Male  Louisiana
2317          Smith          Kaliegh  31.0     Black    Male  Louisiana
2369        Stewart              Kia  17.0     Black    Male  Louisiana
2441     Thibodeaux            Damon  21.0     White    Male  Louisiana
2464      ThYespson             John  22.0     Black    Male  Louisiana
2509       Triplett            Eddie  38.0     Black    Male  Louisiana
2514         Truvia             Earl  17.0     Black    Male  Louisiana
2695       Williams           Archie  22.0     Black    Male  Louisiana
2719       Williams          Michael  31.0     Black    Male  Louisiana
2720       Williams  Michael Anthony  16.0     Black    Male  Louisiana
2730         Willis           Calvin  21.0     Black    Male  Louisiana

                County          Tags        WorstCrimeDisplay  \
16             Orleans         H;#IO                   Murder
37           Jefferson            IO           Sexual Assault
199         Terrebonne         F;#NC  Drug Possession or Sale
207          LA Parish        CV;#IO          Child Sex Abuse
267            Orleans             H                   Murder
268            Orleans     CV;#H;#IO                   Murder
269            Orleans       CIU;#IO                  Robbery
292        St. Tammany            IO           Sexual Assault
300          Jefferson            IO           Sexual Assault
337              Union    CDC;#H;#JI                   Murder
474          Jefferson        CV;#IO                  Robbery
486          Calcasieu            IO           Sexual Assault
551              Caddo     CV;#H;#NC                   Murder
579            Orleans  F;#H;#IO;#NC                   Murder
616          Jefferson         H;#IO                   Murder
626             Iberia            NC  Drug Possession or Sale
643          Jefferson             H                   Murder
668          Jefferson             H                   Murder
814            Orleans         H;#IO                   Murder
820              Caddo             H                   Murder
1082         Jefferson         H;#IO                   Murder
1121           Orleans            IO           Sexual Assault
1176           Orleans   CIU;#IO;#NC                  Robbery
1220         Jefferson           NaN           Sexual Assault
1229         Jefferson           NaN           Sexual Assault
1255        Washington         H;#IO                   Murder
1286            Sabine            IO           Sexual Assault
1321           Orleans       CDC;#IO           Sexual Assault
1327  East Baton Rouge            IO           Sexual Assault
1400           Orleans         H;#IO                   Murder
1429            Iberia     CV;#NC;#P          Child Sex Abuse
1465           Orleans            CV         Attempted Murder
1579         Jefferson        CDC;#H                   Murder
1674         Jefferson         H;#IO                   Murder
1757           Orleans     CV;#H;#IO                   Murder
2033       St. Tammany         F;#NC          Traffic Offense
2148          Orleans            NaN                  Assault
2241           Orleans         H;#IO                   Murder
2317           Orleans    CIU;#H;#IO                   Murder
2369           Orleans    CIU;#H;#IO                   Murder
2441         Jefferson     CV;#H;#IO                   Murder
2464           Orleans        CDC;#H                   Murder
2509           Orleans           NaN  Drug Possession or Sale
2514           Orleans     CV;#H;#IO                   Murder
2695  East Baton Rouge            IO         Attempted Murder
2719         Jefferson         H;#IO                   Murder
2720           Jackson            IO           Sexual Assault
2730             Caddo        CV;#IO          Child Sex Abuse

                           List Add'l Crimes Recode  ... MistakenWitness  \
16                                              NaN  ...             NaN
37                                              NaN  ...             Yes
199                                             NaN  ...             NaN
207                         Burglary/Unlawful Entry  ...             Yes
267                                         Robbery  ...             Yes
268                                             NaN  ...             NaN
269                                             NaN  ...             Yes
292   Other Violent Felony;#Burglary/Unlawful Entry  ...             Yes
300                                             NaN  ...             Yes
337                                         Robbery  ...             NaN
474                                             NaN  ...             Yes
486                         Burglary/Unlawful Entry  ...             Yes
551                                             NaN  ...             NaN
579                                             NaN  ...             NaN
616                                             NaN  ...             NaN
626                                             NaN  ...             NaN
643                                             NaN  ...             NaN
668                                             NaN  ...             NaN
814                                             NaN  ...             NaN
820                                      Conspiracy  ...             NaN
1082                                            NaN  ...             NaN
1121                            Robbery;#Kidnapping  ...             Yes
1176                                            NaN  ...             NaN
1220                                        Robbery  ...             Yes
1229                                            NaN  ...             Yes
1255                                            NaN  ...             Yes
1286                                            NaN  ...             Yes
1321              Manslaughter;#Robbery;#Kidnapping  ...             Yes
1327                                            NaN  ...             Yes
1400                                            NaN  ...             NaN
1429                                            NaN  ...             NaN
1465                                            NaN  ...             Yes
1579                                            NaN  ...             Yes
1674                                            NaN  ...             NaN
1757                                            NaN  ...             NaN
2033                                            NaN  ...             NaN
2148                        Burglary/Unlawful Entry  ...             Yes
2241                                            NaN  ...             Yes
2317                                            NaN  ...             Yes
2369                                            NaN  ...             Yes
2441                                           Rape  ...             Yes
2464                                            NaN  ...             Yes
2509                                            NaN  ...             NaN
2514                                            NaN  ...             NaN
2695                  Rape;#Burglary/Unlawful Entry  ...             Yes
2719                                            NaN  ...             NaN
2720                                            NaN  ...             Yes
2730                                            NaN  ...             Yes

      FalseEvidence  Perjury OfficialMisconduct  ILD Posting Date  \
16              NaN      Yes                Yes  NaN      5/13/14
37              NaN      Yes                Yes  ILD       2/6/18
199             NaN      Yes                Yes  NaN      8/29/11
207             Yes      Yes                Yes  NaN      8/29/11
267             NaN      NaN                Yes  ILD      8/29/11
268             NaN      Yes                Yes  ILD      8/29/11
269             NaN      NaN                Yes  ILD       4/5/21
292             Yes      NaN                Yes  NaN      8/29/11
300             NaN      NaN                NaN  ILD      6/25/14
337             NaN      Yes                Yes  NaN      8/29/11
474             Yes      NaN                NaN  NaN      6/28/19
486             NaN      NaN                NaN  NaN      8/29/11
551             Yes      NaN                Yes  NaN      4/18/17
579             NaN      NaN                NaN  ILD       3/7/19
616             NaN      Yes                Yes  ILD      8/29/11
626             NaN      Yes                Yes  NaN      7/13/17
643             NaN      Yes                Yes  ILD      8/29/11
668             NaN      NaN                Yes  NaN      8/29/11
814             NaN      Yes                Yes  NaN      12/3/18
820             Yes      Yes                Yes  ILD      3/12/14
1082            NaN      NaN                Yes  NaN      8/29/11
1121            NaN      NaN                NaN  NaN       7/3/12
1176            NaN      Yes                NaN  NaN      4/13/21
1220            Yes      NaN                NaN  NaN      8/29/11
1229            NaN      NaN                NaN  ILD      1/13/12
1255            Yes      Yes                Yes  NaN      8/29/11
1286            NaN      NaN                NaN  NaN      8/29/11
1321            NaN      Yes                Yes  NaN      2/24/17
1327            NaN      NaN                Yes  NaN     10/13/18
1400            NaN      Yes                NaN  NaN      8/29/11
1429            NaN      Yes                NaN  NaN     12/17/12
1465            NaN      NaN                NaN  NaN       4/6/20
1579            NaN      Yes                Yes  NaN      8/29/11
1674            NaN      Yes                Yes  ILD      8/29/11
1757            NaN      Yes                Yes  ILD       6/1/16
2033            NaN      Yes                Yes  NaN      8/13/19
2148            NaN      NaN                Yes  NaN      6/30/17
2241            NaN      NaN                NaN  ILD      2/15/18
2317            NaN      Yes                Yes  ILD      6/25/21
2369            NaN      NaN                NaN  ILD      4/15/15
2441            NaN      NaN                Yes  NaN      9/28/12
2464            NaN      Yes                Yes  NaN      8/29/11
2509            NaN      Yes                Yes  NaN      2/11/13
2514            NaN      Yes                Yes  ILD      8/29/11
2695            NaN      NaN                Yes  NaN      3/23/19
2719            NaN      Yes                Yes  NaN      6/18/12
2720            NaN      NaN                NaN  NaN      8/29/11
2730            NaN      NaN                Yes  NaN      8/29/11

                            Yes Tags Date of Crime Year Unnamed: 24  CIU
16       PR;#OF;#WH;#NW;#KP;#PJ;#INT              1,979         NaN  NaN
37                    PR;#OF;#NW;#PJ              1,979         NaN  NaN
199                   PR;#WH;#NW;#PJ              1,977         NaN  NaN
207               PR;#FA;#WH;#NW;#PJ              1,986         NaN  NaN
267                           PR;#WH              1,995         NaN  NaN
268                           PR;#WH              1,975         NaN  NaN
269                           OF;#WT              2,012         NaN  NaN
292                  OF;#WH;#NW;#INT              1,984         NaN  NaN
300                              NaN              1,997         NaN  NaN
337           PR;#OF;#WH;#NW;#KP;#WT              1,986         NaN  NaN
474                              NaN              2,001         NaN  NaN
486                              NaN              1,995         NaN  NaN
551                           PR;#NW              2,012         NaN  NaN
579                              NaN              2,005         NaN  NaN
616                           PR;#WH              1,992         NaN  NaN
626                   OF;#WH;#NW;#PJ              2,010         NaN  NaN
643                           PR;#WH              1,992         NaN  NaN
668                   PR;#WH;#NW;#PL              1,986         NaN  NaN
814          PR;#OF;#WH;#NW;#INT;#PJ              1,980         NaN  NaN
820           PR;#OF;#WH;#NW;#KP;#PJ              1,983         NaN  NaN
1082                          PR;#WH              1,997         NaN  NaN
1121                             NaN              1,992         NaN  NaN
1176                             NaN              1,999         NaN  NaN
1220                             NaN              1,986         NaN  NaN
1229                             NaN              1,981         NaN  NaN
1255              PR;#OF;#WH;#NW;#PJ              1,984         NaN  NaN
1286                             NaN              1,982         NaN  NaN
1321          PR;#OF;#WH;#NW;#WT;#PJ              1,992         NaN  NaN
1327                  PR;#OF;#WH;#NW              1,971         NaN  NaN
1400                             NaN              1,996         NaN  NaN
1429                             NaN              1,987         NaN  NaN
1465                             NaN              2,002         NaN  NaN
1579                          PR;#WH              1,997         NaN  NaN
1674                          PR;#WH              1,992         NaN  NaN
1757  PR;#OF;#WH;#NW;#KP;#WT;#PJ;#PL              1,993         NaN  NaN
2033                  OF;#WH;#NW;#PJ              2,016         NaN  NaN
2148                      OF;#NW;#WT              2,010         NaN  NaN
2241                             NaN              2,004         NaN  NaN
2317          PR;#OF;#WH;#NW;#KP;#WT              2,007         NaN  NaN
2369                             NaN              2,005         NaN  NaN
2441             PR;#OF;#WH;#NW;#INT              1,996         NaN  NaN
2464                  PR;#WH;#NW;#KP              1,984         NaN  NaN
2509          PR;#OF;#WH;#NW;#KP;#PJ              1,998         NaN  NaN
2514                          PR;#WH              1,975         NaN  NaN
2695                      OF;#NW;#WT              1,982         NaN  NaN
2719              PR;#WH;#NW;#KP;#WT              1,996         NaN  NaN
2720                             NaN              1,981         NaN  NaN
2730                      OF;#WH;#NW              1,981         NaN  NaN

[48 rows x 26 columns]
83.47578347578347